Repository Yoast/javascript, pull requests merged in 2019-11, with the labels that each got.

#391 Add API to fix issue with the plugin dev server
  packages/yoastseo/src/worker/createWorker.js
Labels: 0.5, changelog: non-user-facing

#392 Fix console error about event handler in Gutenberg
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
Labels: 0.5, changelog: non-user-facing

#399 Add object-fit: cover to mobile snippet image
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: bugfix

#403 Remove the help center remnants
  .eslintrc
  .travis.yml
  README.md
  apps/components/App.js
  apps/components/HelpCenterWrapper.js
  apps/components/SvgIconsWrapper.js
  apps/components/package.json
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/algolia-search-box/.babelrc
  packages/algolia-search-box/CHANGELOG.MD
  packages/algolia-search-box/babel.config.js
  packages/algolia-search-box/package.json
  packages/algolia-search-box/src/AlgoliaSearcher.js
  packages/algolia-search-box/src/ArticleContent.js
  packages/algolia-search-box/src/Loading.js
  packages/algolia-search-box/src/SearchBar.js
  packages/algolia-search-box/src/SearchResultDetail.js
  packages/algolia-search-box/src/SearchResults.js
  packages/algolia-search-box/src/index.js
  packages/algolia-search-box/tests/AlgoliaSearcherTest.js
  packages/algolia-search-box/tests/ArticleContentTest.js
  packages/algolia-search-box/tests/LoadingTest.js
  packages/algolia-search-box/tests/SearchBarTest.js
  packages/algolia-search-box/tests/SearchResultDetailTest.js
  packages/algolia-search-box/tests/SearchResultsTest.js
  packages/algolia-search-box/tests/__mocks__/@wordpress/i18n.js
  packages/algolia-search-box/tests/__snapshots__/AlgoliaSearcherTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/ArticleContentTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/LoadingTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/SearchBarTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/SearchResultDetailTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/SearchResultsTest.js.snap
  packages/algolia-search-box/tools/jest/setupTests.js
  packages/components/src/HelpCenterButton.js
  packages/components/src/index.js
  packages/components/tests/HelpCenterButtonTest.js
  packages/components/tests/__snapshots__/HelpCenterButtonTest.js.snap
  packages/helpers/tests/__snapshots__/A11yNoticeTest.js.snap
  packages/yoast-components/composites/HelpCenter/views/VideoTutorial.js
  packages/yoast-components/composites/HelpCenter/views/tests/VideoTutorialTest.js
  packages/yoast-components/composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
  packages/yoast-components/composites/Plugin/HelpCenter/HelpCenter.js
  packages/yoast-components/composites/Plugin/HelpCenter/tests/HelpCenterTest.js
  packages/yoast-components/composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
  packages/yoast-components/index.js
  packages/yoast-components/package.json
  yarn.lock
Labels: changelog: other

#407 Set spec folders to the jest environment in eslint configuration.
  .eslintrc
Labels: 0.5, changelog: non-user-facing

#410 Refactor calculateTextIndices and add tests
  packages/yoastseo/spec/parsedPaper/build/tree/cleanup/calculateTextIndicesSpec.js
  packages/yoastseo/src/parsedPaper/build/tree/cleanup/calculateTextIndices.js
Labels: changelog: non-user-facing
