Repository Yoast/javascript, pull requests merged in 2019-04, with the labels that each got.

#175 Add german stemming functionality to internal linking
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/stringProcessing/relevantWordsGermanSpec.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
Labels: Package: yoastseo, needs-code-review lingo

#226 Fix HelpCenter Tabs import.
  packages/yoast-components/composites/Plugin/HelpCenter/HelpCenter.js
  packages/yoast-components/package.json
Labels: 1, Meta

#8 Add focus style to wizard navigation buttons
  packages/configuration-wizard/src/configuration-wizard.scss
  packages/configuration-wizard/src/helpers/_colors.scss
  packages/style-guide/src/_colors.scss
  packages/style-guide/src/colors.json
Labels: UI change
