Repository Yoast/javascript, pull requests merged in 2019-10, with the labels that each got.

#362 Rename messagedata variables
  packages/yoast-components/index.js
  packages/yoast-components/redux/actions/insights.js
  packages/yoast-components/redux/actions/tests/insightsTest.js
  packages/yoast-components/redux/reducers/insights.js
  packages/yoast-components/redux/reducers/prominentWords.js
  packages/yoast-components/redux/reducers/tests/indexTest.js
  packages/yoast-components/redux/reducers/tests/insightsTest.js
  packages/yoast-components/redux/reducers/tests/prominentWordsTest.js
  packages/yoastseo/spec/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/spec/researches/relevantWordsSpec.js
  packages/yoastseo/src/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/researches/relevantWords.js
Labels: changelog: non-user-facing

#365 Make sure the snippet preview image CSS size cannot be altered.
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: enhancement

#367 Emilyatmobtown/add readability score na
  packages/yoastseo/spec/parsedPaper/assess/scoreAggregators/ReadabilityScoreAggregatorSpec.js
  packages/yoastseo/src/parsedPaper/assess/scoreAggregators/ReadabilityScoreAggregator.js
Labels: changelog: enhancement

#368 Add yoast-snippet-preview-container id
  packages/search-metadata-previews/package.json
  packages/search-metadata-previews/src/snippet-preview/FixedWidthContainer.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: changelog: non-user-facing

#378 Adjust custom form controls styling for WP 5.3.
  packages/components/src/input/InputField.js
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
Labels: changelog: enhancement

#382 Set node version in .travis.yml to 10.16
  .travis.yml
Labels: changelog: non-user-facing

#380 Fix snippet preview elements order.
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: changelog: bugfix, changelog: non-user-facing

#379 Remove feature flag from feature branch
  packages/components/src/KeywordSuggestions.js
  packages/components/src/WordList.js
Labels: changelog: other
