Repository Yoast/javascript, pull requests merged in 2019-12, with the labels that each got.

#408 Create mechanism to register custom tree parser
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#415 Update changelog introduction to prevent empty entries
  packages/analysis-report/CHANGELOG.MD
  packages/browserslist-config/CHANGELOG.md
  packages/components/CHANGELOG.MD
  packages/configuration-wizard/CHANGELOG.md
  packages/feature-flag/CHANGELOG.md
  packages/helpers/CHANGELOG.md
  packages/search-metadata-previews/CHANGELOG.md
  packages/style-guide/CHANGELOG.md
  packages/yoast-components/CHANGELOG.MD
  packages/yoast-social-previews/CHANGELOG.md
  packages/yoastseo/CHANGELOG.md
Labels: changelog: non-user-facing

#414 411 drop ie11 support
  packages/analysis-report/.babelrc
  packages/analysis-report/package.json
  packages/components/.babelrc
  packages/components/package.json
  packages/configuration-wizard/.babelrc
  packages/configuration-wizard/package.json
  packages/configuration-wizard/tests/progressIndicatorTest.js
  packages/helpers/.babelrc
  packages/helpers/package.json
  packages/search-metadata-previews/.babelrc
  packages/search-metadata-previews/package.json
  packages/social-metadata-previews/.babelrc
  packages/social-metadata-previews/package.json
  packages/style-guide/.babelrc
  packages/style-guide/package.json
  packages/yoast-components/.babelrc
  packages/yoast-components/package.json
  packages/yoastseo/.babelrc
  packages/yoastseo/package.json
Labels: changelog: non-user-facing

#417 Upgrade content analysis app to latest deps
  apps/content-analysis/.eslintrc
  apps/content-analysis/config/env.js
  apps/content-analysis/config/jest/cssTransform.js
  apps/content-analysis/config/jest/fileTransform.js
  apps/content-analysis/config/modules.js
  apps/content-analysis/config/paths.js
  apps/content-analysis/config/pnpTs.js
  apps/content-analysis/config/webpack.config.js
  apps/content-analysis/config/webpackDevServer.config.js
  apps/content-analysis/package.json
  apps/content-analysis/scripts/build.js
  apps/content-analysis/scripts/start.js
  apps/content-analysis/src/components/AutomaticAnalysis.js
  apps/content-analysis/src/redux/utils/render.js
  apps/content-analysis/src/utils/calculateProminentWords.js
  package.json
  packages/yoast-components/.eslintrc
  yarn.lock
Labels: changelog: non-user-facing

#420 13996 send list of blocks to web worker
  packages/yoastseo/src/values/Paper.js
Labels: changelog: non-user-facing

#422 Add window.location.origin as second argument to the URL constructor
  packages/yoastseo/src/worker/createWorker.js
Labels: changelog: bugfix

#397 Create regular participles in Dutch
  packages/yoastseo/spec/morphology/dutch/generateParticipleFormSpec.js
  packages/yoastseo/src/morphology/dutch/generateParticipleForm.js
  packages/yoastseo/src/morphology/german/generateParticipleForm.js
Labels: 2

#376 Converted snippet preview mode buttons to radio buttons
  packages/components/src/Label.js
  packages/components/src/input/Input.js
  packages/search-metadata-previews/src/snippet-editor/ModeSwitcher.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/tests/SnippetEditorTest.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
Labels: Package: search-metadata-previews, UI change, changelog: enhancement
