Repository Yoast/javascript, pull requests merged in 2019-05, with the labels that each got.

#269 Re-added the refactored feature flag functionality.
  packages/feature-flag/src/index.js
Labels: bug, component: internal linking, innovation

#272 Remove all occurrences of createComponentWithIntl
  apps/components/App.js
  apps/components/package.json
  apps/content-analysis/package.json
  packages/algolia-search-box/package.json
  packages/algolia-search-box/src/SearchResultDetail.js
  packages/algolia-search-box/tests/AlgoliaSearcherTest.js
  packages/algolia-search-box/tests/SearchBarTest.js
  packages/algolia-search-box/tests/SearchResultDetailTest.js
  packages/algolia-search-box/tests/SearchResultsTest.js
  packages/analysis-report/tests/AnalysisResultTest.js
  packages/analysis-report/tests/ContentAnalysisTest.js
  packages/components/tests/NotificationTest.js
  packages/helpers/package.json
  packages/helpers/src/index.js
  packages/helpers/src/tests/createComponentWithIntl.js
  packages/search-metadata-previews/tests/SnippetEditorTest.js
  packages/search-metadata-previews/tests/SnippetPreviewTest.js
  packages/yoast-components/README.md
  packages/yoast-components/composites/HelpCenter/views/tests/VideoTutorialTest.js
  packages/yoast-components/composites/Plugin/HelpCenter/tests/HelpCenterTest.js
  yarn.lock
Labels: 11.2

#276 Allow custom SvgIcon components to be created
  apps/components/SvgIconsWrapper.js
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/algolia-search-box/tests/__snapshots__/SearchResultDetailTest.js.snap
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/SvgIcon.js
  packages/components/tests/__snapshots__/ButtonTest.js.snap
  packages/components/tests/__snapshots__/CollapsibleTest.js.snap
  packages/components/tests/__snapshots__/HelpCenterButtonTest.js.snap
  packages/components/tests/__snapshots__/IconButtonToggleTest.js.snap
  packages/components/tests/__snapshots__/IconLabelledButtonTest.js.snap
  packages/components/tests/__snapshots__/NotificationTest.js.snap
  packages/components/tests/__snapshots__/SvgIconTest.js.snap
  packages/components/tests/__snapshots__/UpsellButtonTest.js.snap
  packages/components/tests/__snapshots__/YoastWarningTest.js.snap
  packages/components/tests/__snapshots__/styledSectionTest.js.snap
  packages/helpers/src/createSvgIconComponent.js
  packages/helpers/src/index.js
  packages/search-metadata-previews/tests/__snapshots__/HelpTextWrapperTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/yoast-components/composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
Labels: 11.3

#281 Added left-margin to the marker button
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
Labels: UI change
