Repository Yoast/javascript, pull requests merged in 2019-09, with the labels that each got.

#345 Change desktop font size to match google
  apps/components/SnippetEditorExample.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: changelog: enhancement

#350 Multi step progress component
  apps/components/App.js
  apps/components/MultiStepProgressWrapper.js
  apps/components/SvgIconsWrapper.js
  apps/components/package.json
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/components/src/MultiStepProgress.js
  packages/components/src/SvgIcon.js
  packages/components/src/index.js
  packages/components/tests/MultiStepProgressTest.js
  packages/components/tests/__snapshots__/MultiStepProgressTest.js.snap
  packages/helpers/src/createSvgIconComponent.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  yarn.lock
Labels: changelog: enhancement

#349 Add an Alert component
  apps/components/ComponentsExample.js
  packages/components/src/Alert.js
  packages/components/src/SvgIcon.js
  packages/components/src/index.js
  packages/components/tests/AlertTest.js
  packages/components/tests/__snapshots__/AlertTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/style-guide/src/_colors.scss
  packages/style-guide/src/colors.json
Labels: changelog: enhancement, underestimated

#325 Add Dutch adjective suffixes to make forms
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/dutch/addAdjectiveSuffixesSpec.js
  packages/yoastseo/src/morphology/dutch/addAdjectiveSuffixes.js
  packages/yoastseo/src/morphology/morphoHelpers/suffixHelpers.js
Labels: 0.5

#359 Pass classname to AlertContainer
  packages/components/src/Alert.js
Labels: changelog: other

#360 Adds a minimum height to every linking suggestion.
  packages/yoast-components/composites/LinkSuggestions/LinkSuggestion.js
Labels: UI change, changelog: bugfix

#358 Add Hungarian transition word list
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/hungarian/transitionWords.js
  packages/yoastseo/src/researches/hungarian/twoPartTransitionWords.js
Labels: development lingo
