Repository Yoast/javascript, pull requests merged in 2020-07, with the labels that each got.

#750 Add Portuguese and Indonesian word form support
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/researches/findKeywordFormsInStringSpec.js
  packages/yoastseo/spec/researches/keywordCountSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/spec/stringProcessing/addWordBoundarySpec.js
  packages/yoastseo/spec/stringProcessing/createRegexFromArray.js
  packages/yoastseo/spec/stringProcessing/createWordRegexSpec.js
  packages/yoastseo/spec/stringProcessing/matchTextWithArraySpec.js
  packages/yoastseo/spec/stringProcessing/matchTextWithWordSpec.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/indonesian/helpers.js
  packages/yoastseo/src/morphology/indonesian/stem.js
  packages/yoastseo/src/morphology/italian/stem.js
  packages/yoastseo/src/morphology/morphoHelpers/findMatchingEndingInArray.js
  packages/yoastseo/src/morphology/portuguese/stem.js
  packages/yoastseo/src/morphology/russian/stem.js
  packages/yoastseo/src/morphology/spanish/stem.js
  packages/yoastseo/src/stringProcessing/addWordboundary.js
  packages/yoastseo/src/stringProcessing/matchTextWithTransliteration.js
Labels: changelog: enhancement

#752 Remove the MentionSuggestion ref since this does not work
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
Labels: changelog: non-user-facing

#758 P1-42 Fix choice component fragment key
  packages/configuration-wizard/src/Choice.js
Labels: changelog: non-user-facing

#754 FRO-209 table component
  packages/components/src/tables/table.css
  packages/components/src/tables/table.html
Labels: UI change, changelog: enhancement

#760 P1 47 Handle small images better
  packages/social-metadata-previews/src/facebook/FacebookImage.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/helpers/determineImageProperties.js
  packages/social-metadata-previews/src/twitter/TwitterImage.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookImageTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookPreviewTest.js.snap
  packages/social-metadata-previews/tests/helpers/determineImagePropertiesTest.js
  packages/social-metadata-previews/tests/twitter/TwitterImageTest.js
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterImageTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterPreviewTest.js.snap
Labels: changelog: non-user-facing

#756 P1-17 export HelpIcon from the root of @yoast/components
  packages/components/src/help-icon/index.js
Labels: changelog: non-user-facing

#759 Update buttons to have disabled and small status
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
Labels: UI change, changelog: enhancement

#764 Remove the border-bottom and margin-top from Collapsible
  packages/components/src/Collapsible.js
Labels: changelog: enhancement

#753 Add Indonesian sentence beginning assessment
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/researches/indonesian/firstWordExceptions.js
Labels: changelog: enhancement

#765 Fix unwanted space type change
  packages/yoastseo/spec/stringProcessing/addWordBoundarySpec.js
  packages/yoastseo/spec/stringProcessing/createRegexFromArray.js
  packages/yoastseo/spec/stringProcessing/createWordRegexSpec.js
  packages/yoastseo/src/stringProcessing/addWordboundary.js
Labels: changelog: non-user-facing

#770 Revert 633
  apps/components/webpack.config.js
  packages/components/src/configuration-wizard/configuration-wizard.css
  packages/components/src/title-separator/title-separator.css
  packages/configuration-wizard/src/Choice.js
  packages/configuration-wizard/src/ConfigurationWizard.js
  packages/configuration-wizard/src/Header.js
  packages/configuration-wizard/src/Step.js
  packages/configuration-wizard/src/StepButton.js
  packages/configuration-wizard/src/StepIndicator.js
  packages/configuration-wizard/src/yoast-theme.js
  packages/configuration-wizard/tests/stepTest.js
Labels: changelog: non-user-facing

#773 Reintroduce Italian and Russian morphology changes for 14.7
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/italian/stem.js
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#761 FRO-212 select2 inline button
  packages/components/src/button/buttons.css
  packages/components/src/select/select.css
  packages/components/src/select/select.html
Labels: UI change, changelog: enhancement

#762 Adds Indonesian transition words assessment
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/indonesian/transitionWords.js
  packages/yoastseo/src/researches/indonesian/twoPartTransitionWords.js
Labels: changelog: enhancement

#772 Add Indonesian sentence length assessment
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
Labels: changelog: non-user-facing

#776 FRO-217 Remove scrollbar from overflow
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/SectionTitle.js
  packages/components/tests/__snapshots__/CollapsibleTest.js.snap
Labels: changelog: non-user-facing

#783 Change the minimal textlength for prominent words calculation
  packages/yoastseo/spec/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/src/researches/getProminentWordsForInternalLinking.js
Labels: changelog: non-user-facing

#777 Add Flesch reading ease assessment for Portuguese
  packages/yoastseo/spec/researches/calculateFleschReadingSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countPortugueseSpec.js
  packages/yoastseo/src/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/config/syllables.js
  packages/yoastseo/src/config/syllables/pt.json
  packages/yoastseo/src/researches/calculateFleschReading.js
Labels: changelog: enhancement

#774 Add handling for small prop
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/button/Button.js
  packages/components/tests/button/ButtonsTest.js
Labels: changelog: enhancement

#781 FRO-218 Updated table component with semrush parts
  packages/components/src/tables/table.css
  packages/components/src/tables/table.html
Labels: UI change

#785 P1 76 Fix site url in social preview
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
Labels: changelog: bugfix

#763 Update morphology data imports
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#786 Add social preview label
  apps/components/SocialPreviewEditorWrapper.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: other

#788 Revert "Update morphology data imports"
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#789 Revert "Revert "Update morphology data imports""
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#782 Show the post type and taxonomy name in the internal linking suggestions
  packages/yoast-components/composites/LinkSuggestions/LinkSuggestion.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: UI change, changelog: enhancement

#775 Add passive voice assessment for Portuguese
  packages/yoastseo/spec/researches/getPassiveVoicePortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getParticiplesPortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsPortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesPortugueseSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getParticiples.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getSentenceParts.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/matchParticiples.js
  packages/yoastseo/src/researches/portuguese/functionWords.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/PortugueseParticiple.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/SentencePart.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/auxiliaries.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/participles.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/stopwords.js
  packages/yoastseo/src/stringProcessing/directPrecedenceExceptionWithoutRegex.js
Labels: changelog: enhancement

#793 Improved internal linking
  packages/yoast-components/composites/LinkSuggestions/LinkSuggestion.js
Labels: UI change, changelog: enhancement

#795 Add Flesch reading and passive voice assessments for Portuguese
  packages/yoastseo/README.md
  packages/yoastseo/spec/researches/calculateFleschReadingSpec.js
  packages/yoastseo/spec/researches/getPassiveVoicePortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getParticiplesPortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsPortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesPortugueseSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countPortugueseSpec.js
  packages/yoastseo/src/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/config/syllables.js
  packages/yoastseo/src/config/syllables/pt.json
  packages/yoastseo/src/researches/calculateFleschReading.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getParticiples.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getSentenceParts.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/matchParticiples.js
  packages/yoastseo/src/researches/portuguese/functionWords.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/PortugueseParticiple.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/SentencePart.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/auxiliaries.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/participles.js
  packages/yoastseo/src/researches/portuguese/passiveVoice/stopwords.js
  packages/yoastseo/src/stringProcessing/directPrecedenceExceptionWithoutRegex.js
Labels: changelog: enhancement

#796 Add readability checks for Indonesian
  packages/yoastseo/README.md
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceIndonesianSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/indonesian/firstWordExceptions.js
  packages/yoastseo/src/researches/indonesian/passiveVoice/nonPassiveVerbsStartingDi.js
  packages/yoastseo/src/researches/indonesian/transitionWords.js
  packages/yoastseo/src/researches/indonesian/twoPartTransitionWords.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/matchParticiples.js
Labels: changelog: enhancement

#784 Same color for placeholder in title and description inputs
  packages/replacement-variable-editor/src/shared.js
Labels: changelog: bugfix

#797 Make the post label fit in container
  packages/yoast-components/composites/LinkSuggestions/LinkSuggestion.js
Labels: changelog: non-user-facing

#802 Fix inconsistency in feedback strings in the Keyphrase in Title assessment
  packages/yoastseo/spec/assessments/TitleKeywordAssessmentSpec.js
  packages/yoastseo/src/assessments/seo/TitleKeywordAssessment.js
Labels: changelog: enhancement

#801 Change the copy sequence
  packages/yoast-components/composites/LinkSuggestions/LinkSuggestions.js
Labels: UI change, changelog: enhancement, component: internal linking

#800 Add hebrew function words
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/hebrew/functionWords.js
Labels: changelog: enhancement

#799 Add table css to monorepo.css
  packages/components/src/index.js
  packages/components/src/tables/index.js
Labels: changelog: non-user-facing

#805 Add hasError prop to KeywordInput component.
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
Labels: changelog: non-user-facing

#806 Add sentence length assessment for Hebrew
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/src/config/content/combinedConfig.js
  packages/yoastseo/src/config/content/he.js
Labels: changelog: enhancement

#798 Add Polish dictionary stemmer
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper3.js
  packages/yoastseo/spec/morphology/polish/stemSpec.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/morphology/polish/stem.js
Labels: changelog: enhancement

#807 Add sentence beginnings assessment for Hebrew
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/researches/hebrew/firstWordExceptions.js
Labels: changelog: enhancement

#810 Lin 495 add function words for arabic
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/arabic/functionWords.js
Labels: changelog: enhancement

#804 Improve sentence tokenization and keyphrase recognition in RTL languages
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/morphology/arabic/createBasicWordFormsArabicSpec.js
  packages/yoastseo/spec/morphology/hebrew/createBasicWordFormsHebrewSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/spec/stringProcessing/getSentencesSpec.js
  packages/yoastseo/src/helpers/getBasicWordForms.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/morphology/arabic/createBasicWordForms.js
  packages/yoastseo/src/morphology/hebrew/createBasicWordForms.js
  packages/yoastseo/src/researcher.js
  packages/yoastseo/src/researches/arabic/functionWords.js
  packages/yoastseo/src/researches/getWordForms.js
  packages/yoastseo/src/researches/hebrew/functionWords.js
  packages/yoastseo/src/stringProcessing/SentenceTokenizer.js
Labels: changelog: enhancement

#809 P1-6 Make Select name optional
  packages/components/src/select/Select.js
Labels: changelog: other

#803 Add transition words assessment for Hebrew
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/hebrew/transitionWords.js
  packages/yoastseo/src/researches/hebrew/twoPartTransitionWords.js
Labels: changelog: enhancement

#811 P3-91 update error styling of keyphrase input
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
Labels: changelog: non-user-facing

#813 Add ability to pass refs to buttons and buttonstyledlinks
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/button/Button.js
Labels: changelog: enhancement
