Repository Yoast/javascript, pull requests merged in 2020-03, with the labels that each got.

#528 Add specs for prefixed irregular verbs
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
Labels: changelog: non-user-facing

#527 Create rules to stem superlatives
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#531 LIN 301 Use stoplists in stemming rules
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#532 Lin 269 test words ending in t or d
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/stemTOrDFromEndOfWordSpec.js
  packages/yoastseo/src/morphology/dutch/stemTOrDFromEndOfWord.js
Labels: changelog: enhancement

#502 Add css for button component
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
Labels: changelog: non-user-facing

#539 Rework html to include a11y
  packages/components/src/modal/modal-mobile-collapsible.html
  packages/components/src/modal/modal-react-tabs.html
  packages/components/src/modal/modal-without-nav.html
  packages/components/src/modal/modal.css
Labels: changelog: bugfix

#541 Feature/admin redesign
  packages/components/src/base/borders.css
  packages/components/src/base/colors.css
  packages/components/src/base/icons.css
  packages/components/src/base/root.css
  packages/components/src/base/typography.css
  packages/components/src/base/utility.css
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
  packages/components/src/checkbox/checkbox.css
  packages/components/src/checkbox/checkbox.html
  packages/components/src/data-model/data-model.css
  packages/components/src/data-model/data-model.html
  packages/components/src/field-group/field-group.css
  packages/components/src/inputs/input.css
  packages/components/src/inputs/input.html
  packages/components/src/modal/modal-mobile-collapsible.html
  packages/components/src/modal/modal-react-tabs.html
  packages/components/src/modal/modal-without-nav.html
  packages/components/src/modal/modal.css
  packages/components/src/radiobutton/radiobutton.css
  packages/components/src/radiobutton/radiobutton.html
  packages/components/src/select/select.css
  packages/components/src/select/select.html
  packages/components/src/toggle/toggle.css
  packages/components/src/toggle/toggle.html
Labels: UI change, changelog: non-user-facing

#534 Add specs for adjectives ending in -e
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
Labels: changelog: non-user-facing

#535 Add specs for nouns that look like participles
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
Labels: changelog: non-user-facing

#545 Remove unapproved and unnecessary buttons
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
Labels: UI change, changelog: non-user-facing

#538 Improve stemming specs for Dutch
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/stemSpec.js
Labels: changelog: non-user-facing

#547 Add past plural of verbs in zen and ven
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/getStemWordsWithTAndDEndingSpecs.js
  packages/yoastseo/src/morphology/dutch/getStemWordsWithTAndDEnding.js
Labels: changelog: enhancement

#543 Add Dutch word form support
  apps/.DS_Store
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/dutch/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/generateParticipleFormSpec.js
  packages/yoastseo/spec/morphology/dutch/getStemWordsWithTAndDEndingSpecs.js
  packages/yoastseo/spec/morphology/dutch/stemSpec.js
  packages/yoastseo/spec/morphology/dutch/stemTOrDFromEndOfWordSpec.js
  packages/yoastseo/spec/morphology/german/helpersSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/checkExceptionsWithFullFormsSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/exceptionListHelpersSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/flattenSortLength.js
  packages/yoastseo/spec/morphology/morphoHelpers/regexHelpersSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/dutch/detectAndStemRegularParticiple.js
  packages/yoastseo/src/morphology/dutch/detectAndStemSuffixes.js
  packages/yoastseo/src/morphology/dutch/determineStem.js
  packages/yoastseo/src/morphology/dutch/generateParticipleForm.js
  packages/yoastseo/src/morphology/dutch/getStemWordsWithTAndDEnding.js
  packages/yoastseo/src/morphology/dutch/stem.js
  packages/yoastseo/src/morphology/dutch/stemModificationHelpers.js
  packages/yoastseo/src/morphology/dutch/stemTOrDFromEndOfWord.js
  packages/yoastseo/src/morphology/german/determineStem.js
  packages/yoastseo/src/morphology/morphoHelpers/checkExceptionsWithFullForms.js
  packages/yoastseo/src/morphology/morphoHelpers/exceptionListHelpers.js
  packages/yoastseo/src/morphology/morphoHelpers/flattenSortLength.js
  packages/yoastseo/src/morphology/morphoHelpers/regexHelpers.js
  packages/yoastseo/src/morphology/morphoHelpers/stemHelpers.js
Labels: changelog: enhancement

#549 Bundle CSS from components package
  packages/analysis-report/package.json
  packages/analysis-report/tools/jest/CSSStub.js
  packages/components/README.md
  packages/components/jest/CSSStub.js
  packages/components/package.json
  packages/components/src/base/index.js
  packages/components/src/button/index.js
  packages/components/src/checkbox/index.js
  packages/components/src/data-model/index.js
  packages/components/src/field-group/index.js
  packages/components/src/index.js
  packages/components/src/inputs/index.js
  packages/components/src/modal/index.js
  packages/components/src/radiobutton/index.js
  packages/components/src/select/index.js
  packages/components/src/toggle/index.js
  packages/configuration-wizard/package.json
  packages/configuration-wizard/tools/jest/CSSStub.js
  packages/search-metadata-previews/package.json
  packages/search-metadata-previews/tests/CSSStub.js
  packages/yoast-components/jest/__mocks__/styleMock.js
Labels: changelog: non-user-facing

#551 Add FieldGroup and Input components
  apps/components/App.js
  apps/components/ReactifiedComponentsWrapper.js
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/components/src/GenerateId.js
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/inputs/TextArea.js
  packages/components/src/inputs/TextInput.js
  packages/components/tests/GenerateIdTest.js
  packages/components/tests/inputs/TextAreaTest.js
  packages/components/tests/inputs/TextInputTest.js
Labels: changelog: non-user-facing

#571 LIN 321 Add specs for plural nouns ending in -ors
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
Labels: changelog: non-user-facing

#578 Add specs for Spanish verbs ending in -egir and -igir
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
Labels: changelog: non-user-facing

#562 Create RadioButtonGroup component
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/radiobutton/RadioButtonGroup.js
  packages/components/tests/RadioButtonGroupTest.js
Labels: changelog: non-user-facing

#575 Add CSS for multiselect
  packages/components/src/base/colors.css
  packages/components/src/select/select.css
  packages/components/src/select/select.html
Labels: UI change, changelog: non-user-facing

#582 Avoids verbal stemming of Spanish non-verbs that look like verbs
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#583 Add rules to stem diminutives
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#585 Add rules to check exceptions full forms before stemming
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#537 implemented url inputfield and action to set image
  packages/components/src/index.js
  packages/social-metadata-forms/jest/__mocks__/styleMock.js
  packages/social-metadata-forms/package.json
  packages/social-metadata-forms/src/ImageSelect.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-forms/src/redux/actions/formActions.js
  packages/social-metadata-forms/src/redux/reducers/formReducer.js
  packages/social-metadata-forms/tests/ImageSelectTest.js
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
  packages/social-metadata-forms/tests/redux/actions/formActionsTest.js
  packages/social-metadata-forms/tests/redux/reducers/formReducerTest.js
Labels: changelog: non-user-facing

#587 Create helpicon and update styles
  packages/components/src/base/colors.css
  packages/components/src/checkbox/checkbox.html
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/field-group/field-group.css
  packages/components/src/help-icon/HelpIcon.js
  packages/components/src/help-icon/help-icon.css
  packages/components/src/help-icon/help-icon.html
  packages/components/src/inputs/input.html
  packages/components/src/radiobutton/radiobutton.html
  packages/components/src/select/select.html
  packages/components/src/toggle/toggle.html
Labels: changelog: enhancement
