Repository Yoast/javascript, pull requests merged in 2020-06, with the labels that each got.

#694 Fix stemming of Indonesian words beginning with m- with prefix -pem/mem
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#687 Stem French verbs with -ons suffix
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#700 FRO-94 Fix placement modal close button
  packages/components/src/Modal.js
  packages/components/src/modal/modal.css
Labels: UI change, changelog: bugfix

#698 Create reactified button components
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/button/Button.js
  packages/components/src/button/Icon.js
  packages/components/src/button/Primary.js
  packages/components/src/button/Secondary.js
  packages/components/src/button/Text.js
  packages/components/src/button/Upsell.js
  packages/components/src/button/buttons.html
  packages/components/src/button/index.js
  packages/components/tests/button/ButtonsTest.js
  packages/components/tests/button/__snapshots__/ButtonsTest.js.snap
Labels: changelog: enhancement

#702 FRO-95 Add namespace to CSS variables
  packages/components/src/base/borders.css
  packages/components/src/base/colors.css
  packages/components/src/base/icons.css
  packages/components/src/base/typography.css
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
  packages/components/src/checkbox/checkbox.css
  packages/components/src/checkbox/checkbox.html
  packages/components/src/data-model/DataModel.js
  packages/components/src/data-model/data-model.css
  packages/components/src/data-model/data-model.html
  packages/components/src/field-group/field-group.css
  packages/components/src/help-icon/help-icon.css
  packages/components/src/help-icon/help-icon.html
  packages/components/src/inputs/input.css
  packages/components/src/inputs/input.html
  packages/components/src/modal/modal-mobile-collapsible.html
  packages/components/src/modal/modal-react-tabs.html
  packages/components/src/modal/modal-without-nav.html
  packages/components/src/modal/modal.css
  packages/components/src/radiobutton/radiobutton.css
  packages/components/src/radiobutton/radiobutton.html
  packages/components/src/select/select.css
  packages/components/src/select/select.html
  packages/components/src/title-separator/title-separator.css
  packages/components/src/title-separator/title-separator.html
  packages/components/src/toggle/toggle.css
  packages/components/src/toggle/toggle.html
  packages/components/tests/__snapshots__/DataModelTest.js.snap
  packages/components/tests/__snapshots__/WordOccurrencesTest.js.snap
Labels: changelog: bugfix

#699 Add focus styling to elements
  packages/components/src/base/colors.css
  packages/components/src/button/buttons.css
  packages/components/src/inputs/input.css
  packages/components/src/select/select.css
  packages/components/src/toggle/toggle.css
Labels: UI change, changelog: enhancement

#697 Improve stemming Indonesian suffixes -kan and -an
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/helpers.js
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#707 Fro 93 update styling reactified buttons
  packages/components/src/button/buttons.css
Labels: UI change, changelog: enhancement

#712 Add check for stemming exceptions to the Russian stemmer
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#691 Add function words for Indonesian
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/stringProcessing/relevantWordsIndonesianSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/indonesian/functionWords.js
Labels: changelog: enhancement

#711 Add Italian irregular diminutives
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/italian/stem.js
  packages/yoastseo/src/researches/italian/functionWords.js
Labels: changelog: enhancement

#710 P3-32 Adjust styling for the related keyphrases modal
  packages/components/src/modal/modal-mobile-collapsible.html
  packages/components/src/modal/modal-without-nav.html
  packages/components/src/modal/modal.css
Labels: changelog: non-user-facing

#714 Add one transition word for Russian
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/src/researches/russian/transitionWords.js
Labels: changelog: enhancement

#695 Add rules for stemming exceptions on ter- and keter-
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#715 FRO 104 Add type="button" to buttons
  packages/components/src/button/Button.js
  packages/components/src/button/buttons.html
Labels: changelog: enhancement

#678 Update styling after UX check
  packages/replacement-variable-editor/src/shared.js
  packages/social-metadata-forms/src/ImageSelect.js
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
  packages/social-metadata-previews/src/facebook/FacebookImage.js
  packages/social-metadata-previews/src/twitter/TwitterImage.js
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookImageTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookPreviewTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterImageTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterPreviewTest.js.snap
Labels: changelog: non-user-facing

#717 Make 'Close' in Icon.js translatable
  packages/components/src/button/Icon.js
Labels: changelog: non-user-facing

#633 Style update wizard radiobuttons and inputfields
  apps/components/package.json
  apps/components/webpack.config.js
  packages/components/src/title-separator/title-separator.css
  packages/configuration-wizard/package.json
  packages/configuration-wizard/src/Choice.js
  packages/configuration-wizard/src/ConfigurationWizard.js
  packages/configuration-wizard/src/Header.js
  packages/configuration-wizard/src/Step.js
  packages/configuration-wizard/src/StepButton.js
  packages/configuration-wizard/src/StepIndicator.js
  packages/configuration-wizard/src/configuration-wizard.scss
  packages/configuration-wizard/src/yoast-theme.js
  packages/configuration-wizard/tests/stepTest.js
Labels: UI change, changelog: enhancement

#709 Add exception checks for irregular nouns to the Russian stemmer
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#722 Remove the width styling from a Yoast Data Model
  packages/components/src/data-model/data-model.css
Labels: 0.5, changelog: bugfix

#720 Add rule for prefix-changing exception words with peng-
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#713 Lin 434 indonesian single syllable words
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#721 Add a private key and certificate so that openssl does not complain
  apps/components/certificate.pem
  apps/components/package.json
  apps/components/privatekey.pem
Labels: changelog: non-user-facing

#723 Improve stemming of verb plurals on -ons
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#708 Also stem derivational suffixes at start of stemming
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#668 FRO-11 update styling form fields settings pages
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/buttons/Button.js
  packages/components/src/index.js
  packages/components/src/select/select.css
  packages/components/src/title-separator/index.js
  packages/components/src/toggle/toggle.css
  packages/components/tests/__snapshots__/AlertTest.js.snap
  packages/components/tests/__snapshots__/ButtonTest.js.snap
  packages/components/tests/__snapshots__/CollapsibleTest.js.snap
  packages/components/tests/__snapshots__/IconLabelledButtonTest.js.snap
  packages/components/tests/__snapshots__/LinkButtonTest.js.snap
  packages/replacement-variable-editor/src/Mention.js
  packages/replacement-variable-editor/src/shared.js
  packages/search-metadata-previews/tests/__snapshots__/HelpTextWrapperTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
  packages/style-guide/src/colors.json
Labels: UI change, changelog: enhancement

#716 PLAT-282 updated to react and react-dom 16.9.0
  apps/components/package.json
  packages/components/package.json
Labels: changelog: non-user-facing

#726 Add specs for the irregular French verbs
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
Labels: changelog: enhancement

#725 Add disabled state for toggles
  packages/components/src/button/buttons.css
  packages/components/src/toggle/toggle.css
Labels: UI change, changelog: enhancement

#696 Add stemming for Indonesian reduplicated plurals
  packages/yoastseo/grunt/config/eslint.js
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/researches/findKeywordFormsInStringSpec.js
  packages/yoastseo/spec/researches/keywordCountSpec.js
  packages/yoastseo/spec/stringProcessing/addWordBoundarySpec.js
  packages/yoastseo/spec/stringProcessing/matchTextWithArraySpec.js
  packages/yoastseo/spec/stringProcessing/matchTextWithWordSpec.js
  packages/yoastseo/src/morphology/indonesian/stem.js
  packages/yoastseo/src/stringProcessing/addWordboundary.js
  packages/yoastseo/src/stringProcessing/matchTextWithTransliteration.js
Labels: changelog: enhancement

#728 Define property Type on ReplacementVariableEditor
  packages/search-metadata-previews/src/snippet-editor/SettingsSnippetEditorFields.js
Labels: changelog: non-user-facing

#727 Introduce IDs for QA
  packages/social-metadata-forms/src/ImageSelect.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-forms/tests/ImageSelectTest.js
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
Labels: changelog: non-user-facing

#729 Use preview fallbacks and input placeholders
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: enhancement

#724 Improve stemming single syllable words
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#734 Add a dependency on the replacement variable editor in search metadata
  packages/search-metadata-previews/package.json
Labels: changelog: non-user-facing

#738 Fix styling for variables on search appearance page
  packages/replacement-variable-editor/src/Mention.js
Labels: changelog: bugfix

#739 Remove react and react-dom aliases from content analysis app webpack config
  apps/content-analysis/config/paths.js
  apps/content-analysis/config/webpack.config.js
Labels: changelog: other

#746 FRO-145 shadow and border toggle switch
  packages/components/src/toggle/toggle.css
Labels: UI change, changelog: enhancement

#748 Fix the proptype for choices
  packages/configuration-wizard/src/Choice.js
Labels: changelog: bugfix

#745 Removes standard Wordpress checkmark
  packages/components/src/checkbox/checkbox.css
Labels: UI change, changelog: non-user-facing

#749 Always show enabled toggle right
  packages/components/src/toggle/toggle.css
Labels: changelog: non-user-facing

#735 LIN-416 Improve sentence tokenization for languages written in Hebrew and Arabic script
  packages/yoastseo/spec/stringProcessing/getSentencesSpec.js
  packages/yoastseo/src/stringProcessing/SentenceTokenizer.js
Labels: changelog: enhancement

#733 Add Indonesian pseudo-plurals
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#736 Add checks for words that look like they begin with a valid prefix
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#744 Improve feedback strings of the Keyphrase in Title assessment
  packages/yoastseo/spec/assessments/TitleKeywordAssessmentSpec.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper4.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper2.js
  packages/yoastseo/src/assessments/seo/TitleKeywordAssessment.js
Labels: changelog: enhancement

#740 Add a check for keywords containing a dash
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper1.js
  packages/yoastseo/spec/researches/keywordCountInUrlSpec.js
  packages/yoastseo/src/researches/keywordCountInUrl.js
Labels: changelog: enhancement
