Repository Yoast/javascript, pull requests merged in 2020-10, with the labels that each got.

#876 P3-202 Fix SEMrush labels stylings using Yoast CSS vars
  packages/components/src/field-group/field-group.css
  packages/components/src/tables/table.css
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
Labels: changelog: enhancement

#870 LIN-625 Add special quotation marks to wordBoundaries
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/spec/researches/german/passiveVoice/ParticipleSpec.js
  packages/yoastseo/spec/stringProcessing/matchWordInSentenceSpec.js
  packages/yoastseo/spec/stringProcessing/removePunctuationSpec.js
  packages/yoastseo/src/config/wordBoundaries.js
  packages/yoastseo/src/researches/german/passiveVoice/GermanParticiple.js
  packages/yoastseo/src/stringProcessing/removePunctuation.js
Labels: changelog: bugfix

#878 P3-184 changes for zapier ui
  packages/components/src/base/colors.css
  packages/components/src/button/buttons.css
  packages/components/src/field-group/field-group.css
  packages/components/src/inputs/input.css
  packages/components/src/inputs/input.html
Labels: changelog: enhancement

#880 Prepare Swedish morphology for 15.2 release
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper2.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/swedish/stemSpec.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/swedish/stem.js
Labels: changelog: non-user-facing

#879 LIN-640 Only give reading time result for English
  packages/yoastseo/spec/researches/readingTimeSpec.js
  packages/yoastseo/src/researches/readingTime.js
Labels: changelog: non-user-facing

#877 Add Hebrew stemmer
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/hebrew/stemSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/hebrew/stem.js
Labels: changelog: enhancement, innovation

#869 Add passive voice assessment for Hebrew
  packages/yoastseo/spec/researches/getPassiveVoiceHebrewSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsHufal.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsNifal.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsPual.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: enhancement

#881 Fix Select's onOptionFocus call
  packages/components/src/select/Select.js
Labels: changelog: bugfix

#882 Add multiletter prefixes for Arabic
  packages/yoastseo/spec/morphology/arabic/createBasicWordFormsArabicSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/morphology/arabic/createBasicWordForms.js
Labels: changelog: enhancement

#865 Add prototype assessment for ranking intentions
  packages/yoastseo/spec/assessments/SingularPluralAssessmentPrototypeSpec.js
  packages/yoastseo/spec/researches/countSingularAndPluralNounsSpec.js
  packages/yoastseo/src/assessments/index.js
  packages/yoastseo/src/assessments/seo/SingularPluralAssessmentPrototype.js
  packages/yoastseo/src/researcher.js
  packages/yoastseo/src/researches/countSingularAndPluralNouns.js
  packages/yoastseo/src/seoAssessor.js
Labels: changelog: enhancement

#743 Test the performance of a Polish dictionary stemmer
  apps/content-analysis/package-lock.json
  apps/content-analysis/package.json
  apps/content-analysis/src/App.js
  apps/content-analysis/src/components/Controls.js
  apps/content-analysis/src/utils/runKeyphraseAnalysis.js
  package.json
  packages/.DS_Store
  packages/yoastseo/.DS_Store
  packages/yoastseo/package-lock.json
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.html
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.html
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.html
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  yarn.lock
Labels: changelog: non-user-facing, innovation

#891 Refactor the keywordCount research
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/researches/keywordCount.js
Labels: changelog: non-user-facing

#892 Refactor matchKeywordInSubheadings
  packages/yoastseo/src/languageProcessing/languages/_default/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/researches/base/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#893 Refactor keywordCountInUrl.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/researches/keywordCountInUrl.js
Labels: changelog: non-user-facing

#898 Delete unused passive voice helper files
  packages/yoastseo/src/languageProcessing/helpers/_todo/directPrecedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/_todo/precedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/directPrecedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/precedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/word/precedesIndex.js
  packages/yoastseo/src/languageProcessing/languages/en/config/passiveVoice/EnglishParticiple.js
  packages/yoastseo/src/languageProcessing/languages/es/config/passiveVoice/SpanishParticiple.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/passiveVoice/FrenchParticiple.js
  packages/yoastseo/src/languageProcessing/languages/it/config/passiveVoice/ItalianParticiple.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/passiveVoice/DutchParticiple.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/passiveVoice/PolishParticiple.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/passiveVoice/PortugueseParticiple.js
Labels: changelog: non-user-facing

#895 Add Hebrew full-texts tests
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
Labels: changelog: non-user-facing

#902 Refactor src helper files
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/helpers/SyllableCountStepSpec.js
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/helpers/getLanguageAvailabilitySpec.js
  packages/yoastseo/spec/helpers/getLanguageSpec.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/helpers/retrieveStemmerSpec.js
  packages/yoastseo/spec/helpers/syllableCountIteratorSpec.js
  packages/yoastseo/spec/helpers/syllableCountSpec.js
  packages/yoastseo/src/config/_todo/content/combinedConfig.js
  packages/yoastseo/src/config/_todo/syllables.js
  packages/yoastseo/src/config/transliterations.js
  packages/yoastseo/src/helpers/_todo/getBasicWordForms.js
  packages/yoastseo/src/helpers/_todo/getFunctionWords.js
  packages/yoastseo/src/helpers/_todo/getFunctionWordsLanguages.js
  packages/yoastseo/src/helpers/_todo/getLanguageAvailability.js
  packages/yoastseo/src/helpers/_todo/getLanguagesWithWordFormSupport.js
  packages/yoastseo/src/helpers/_todo/getStemForLanguage.js
  packages/yoastseo/src/helpers/_todo/index.js
  packages/yoastseo/src/helpers/_todo/retrieveStemmer.js
  packages/yoastseo/src/languageProcessing/helpers/language/getLanguage.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/count.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountIterator.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountStep.js
  packages/yoastseo/src/parsedPaper/assess/scoreAggregators/ReadabilityScoreAggregator.js
  packages/yoastseo/src/scoring/assessments/readability/paragraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/subheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/textPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/wordComplexityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
Labels: changelog: non-user-facing

#906 Refactor assessments that use language availability check for their applicability
  packages/yoastseo/src/scoring/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/keywordStopWordsAssessment.js
Labels: changelog: non-user-facing

#903 Add words to the passive exceptions for English
  packages/yoastseo/src/researches/english/passiveVoice/irregulars.js
  packages/yoastseo/src/researches/english/passiveVoice/non-verb-ending-ed.js
Labels: changelog: enhancement

#890 Refactor buildTopicStems.js & getWordForms.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/buildTopicStems.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/getAllWordsFromPaper.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ca/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/hu/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/researches/base/getWordForms.js
Labels: changelog: non-user-facing

#907 Refactor yoastseo/src/config files
  packages/yoastseo/index.js
  packages/yoastseo/src/app.js
  packages/yoastseo/src/config/_todo/removalWords.js
  packages/yoastseo/src/config/_todo/stopwords.js
  packages/yoastseo/src/config/_todo/syllables.js
  packages/yoastseo/src/config/config.js
  packages/yoastseo/src/config/index.js
  packages/yoastseo/src/config/presenter.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/scoring/renderers/AssessorPresenter.js
  packages/yoastseo/src/snippetPreview/snippetPreview.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#910 LINGO-328 Merge Hebrew feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/morphology/hebrew/stemSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceHebrewSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/config/content/combinedConfig.js
  packages/yoastseo/src/config/content/he.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/morphology/hebrew/stem.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/hebrew/firstWordExceptions.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsHufal.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsNifal.js
  packages/yoastseo/src/researches/hebrew/passiveVoice/regularRootsPual.js
  packages/yoastseo/src/researches/hebrew/transitionWords.js
  packages/yoastseo/src/researches/hebrew/twoPartTransitionWords.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: enhancement
