Repository Yoast/javascript, pull requests merged in 2020-05, with the labels that each got.

#638 CSS fixes for image upload component
  packages/components/src/button/buttons.css
  packages/components/src/inputs/input.css
Labels: UI change, changelog: non-user-facing

#646 Move Polish stemming data to morphology data file
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper3.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/polish/stemSpec.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/polish/stem.js
Labels: changelog: non-user-facing

#656 Add full forms and multiple stems exception checks for French
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#655 Update non-English morphology data imports to version 6
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#654 Change Warning component colors
  packages/components/src/Warning.js
  packages/components/tests/__snapshots__/YoastWarningTest.js.snap
Labels: changelog: enhancement

#642 Transfer data from French stemmer to data file
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/morphoHelpers/regexHelpersSpec.js
  packages/yoastseo/src/morphology/french/stem.js
  packages/yoastseo/src/morphology/morphoHelpers/regexHelpers.js
Labels: changelog: enhancement

#663 French morphology part 2
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/morphoHelpers/regexHelpersSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/morphology/french/stem.js
  packages/yoastseo/src/morphology/morphoHelpers/regexHelpers.js
Labels: changelog: non-user-facing

#662 Add an exception check for plurals ending on -x
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#661 Add Russian morphology support
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#660 Fix Twitter Title and Description styles in metabox
  packages/social-metadata-previews/src/twitter/TwitterDescription.js
  packages/social-metadata-previews/src/twitter/TwitterTitle.js
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterDescriptionTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterPreviewTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterTitleTest.js.snap
Labels: changelog: bugfix

#659 Placeholders for description (via props) and for title (via replacevars)
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: enhancement

#666 Add exception check for French words ending in -s that should not be stemmed
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#670 Fix stemming of french words on ent
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#671 Add exception check for short French words that are not stemmed but should be
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#673 Add support for irregular Italian participles
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/italian/stem.js
Labels: changelog: enhancement

#674 French morphology part 3
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: non-user-facing

#672 Add specs for absolute superlative suffixes
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/goldStandardStems.json
Labels: changelog: enhancement

#675 Add Italian morphology support
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/italian/stem.js
  packages/yoastseo/src/morphology/morphoHelpers/createRulesFromMorphologyData.js
Labels: changelog: enhancement

#677 Update non-English morphology data imports to v7
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#676 FRO-78 Add extra specificity for select2 pulldowns
  packages/components/src/select/Select.js
  packages/components/src/select/select.css
Labels: changelog: bugfix

#679 Fix typos in Italian gold standard list
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/goldStandardStems.json
Labels: changelog: non-user-facing

#667 Transfer Portuguese stemming data to morphology data file
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/portuguese/stem.js
Labels: changelog: non-user-facing

#680 Add exception check for French verbs with multiple stems
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#683 Fixes infinitives stemming in Russian
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#693 Add the remaining buttons
  packages/components/src/button/buttons.css
  packages/components/src/button/buttons.html
Labels: UI change

#688 Add specs for the French suffix -ition and edit the goldStandard list
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
Labels: changelog: non-user-facing
