Repository Yoast/javascript, pull requests merged in 2020-08, with the labels that each got.

#817 Add a new active schema icon
  packages/components/src/base/icons.css
Labels: changelog: enhancement

#819 Add spec for sentence length assessment in Arabic
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
Labels: changelog: non-user-facing

#820 Remove Hebrew functionality from 14.8
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/helpers/getBasicWordForms.js
  packages/yoastseo/src/helpers/getFunctionWords.js
Labels: changelog: non-user-facing

#818 Add sentence beginnings assessment for Arabic
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/researches/arabic/firstWordExceptions.js
Labels: changelog: enhancement

#812 Add transition words assessment for Arabic
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/arabic/transitionWords.js
  packages/yoastseo/src/researches/arabic/twoPartTransitionWords.js
Labels: changelog: enhancement

#821 Add an edit icon button
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/base/icons.css
  packages/components/src/button/Button.js
  packages/components/src/button/buttons.css
Labels: changelog: enhancement

#814 P3-90 Refactored error messages to be displayed as unordered list
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
  packages/yoast-components/composites/Plugin/Shared/tests/KeywordInputTest.js
Labels: changelog: non-user-facing

#822 Improve Hebrew keyphrase recognition
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/helpers/getBasicWordForms.js
  packages/yoastseo/src/helpers/getFunctionWords.js
Labels: changelog: enhancement

#823 Make feedback strings in the keyphrase in subheadings assessment more explicit
  packages/yoastseo/spec/assessments/SubHeadingsKeywordAssessmentSpec.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/src/assessments/seo/SubHeadingsKeywordAssessment.js
Labels: changelog: enhancement

#824 Add Polish word form functionality
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper3.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/polish/stemSpec.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/polish/stem.js
Labels: changelog: enhancement

#826 [QAK-2159] Open keyword research guide link in a new tab
  packages/components/CHANGELOG.MD
  packages/components/src/WordOccurrenceInsights.js
Labels: changelog: enhancement

#828 Add more Polish function words
  packages/yoastseo/spec/stringProcessing/determineProminentWordsPolishSpec.js
  packages/yoastseo/spec/stringProcessing/relevantWordsPolishSpec.js
  packages/yoastseo/src/researches/polish/functionWords.js
Labels: changelog: enhancement

#829 Add Arabic passive voice assessment
  packages/yoastseo/spec/researches/getPassiveVoiceArabicSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/researches/arabic/passiveVoice/passiveVerbsWithLongVowel.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: enhancement

#830 P3 114 match the keyphrase input errors
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
Labels: UI change, changelog: enhancement

#825 Add styling for the yoast icon and the post settings modal
  packages/components/src/index.js
  packages/components/src/modal/index.js
  packages/components/src/modal/modal.css
Labels: changelog: non-user-facing

#832 Add two missing prefixes to the list of ignored prefixes for Arabic
  packages/yoastseo/spec/morphology/arabic/createBasicWordFormsArabicSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/morphology/arabic/createBasicWordForms.js
Labels: changelog: enhancement

#834 Render select2 dropdown so that it appears on top of modal
  packages/components/src/select/select.css
Labels: changelog: bugfix

#835 Add RTL support for the replacement suggestions
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/helpers/positionSuggestions.js
  packages/replacement-variable-editor/tests/ReplacementVariableEditorTest.js
  packages/replacement-variable-editor/tests/positionSuggestionsTest.js
Labels: changelog: bugfix

#833 Prepare Arabic readability for 15.0 release
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceArabicSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/arabic/firstWordExceptions.js
  packages/yoastseo/src/researches/arabic/passiveVoice/passiveVerbsWithLongVowel.js
  packages/yoastseo/src/researches/arabic/transitionWords.js
  packages/yoastseo/src/researches/arabic/twoPartTransitionWords.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: enhancement

#837 Introduces the example icons.html
  packages/components/src/base/icons.html
Labels: changelog: other

#836 Socials: change width to max-width
  packages/social-metadata-previews/src/facebook/FacebookDescription.js
  packages/social-metadata-previews/src/facebook/FacebookImage.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/twitter/TwitterDescription.js
  packages/social-metadata-previews/src/twitter/TwitterImage.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookDescriptionTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookImageTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookPreviewTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterDescriptionTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterImageTest.js.snap
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterPreviewTest.js.snap
Labels: changelog: bugfix

#838 Make Select and RadioButtons respond to props
  packages/components/src/radiobutton/RadioButtonGroup.js
  packages/components/src/select/Select.js
  packages/components/tests/SelectTest.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
Labels: changelog: other

#839 Replace Select2 with react-select for our multiselect
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/package.json
  packages/components/src/internal/ErrorBoundary.js
  packages/components/src/internal/ErrorWithUrl.js
  packages/components/src/internal/YoastError.js
  packages/components/src/select/Select.js
  packages/components/src/select/select.css
  packages/components/tests/SelectTest.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
  yarn.lock
Labels: changelog: other

#842 Add more English transition words
  packages/yoastseo/src/researches/english/transitionWords.js
Labels: changelog: enhancement

#843 P1-151 Fix Facebook image width for non-landscape images
  packages/social-metadata-previews/src/facebook/FacebookImage.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookImageTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookPreviewTest.js.snap
Labels: changelog: non-user-facing

#840 Let prominent words threshold be dependent on the availability of morphology data
  packages/yoastseo/spec/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/src/researches/getProminentWordsForInternalLinking.js
Labels: changelog: other

#841 Add Arabic and Urdu punctuation marks for word tokenization
  packages/yoastseo/spec/stringProcessing/addWordBoundarySpec.js
  packages/yoastseo/spec/stringProcessing/createRegexFromArray.js
  packages/yoastseo/spec/stringProcessing/createRegexFromArraySpec.js
  packages/yoastseo/spec/stringProcessing/createWordRegexSpec.js
  packages/yoastseo/spec/stringProcessing/getWordsSpec.js
  packages/yoastseo/spec/stringProcessing/matchTextWithWordSpec.js
  packages/yoastseo/spec/stringProcessing/matchWordInSentenceSpec.js
  packages/yoastseo/spec/stringProcessing/removePunctuationSpec.js
  packages/yoastseo/spec/stringProcessing/stripWordBoundariesSpec.js
  packages/yoastseo/src/config/wordBoundaries.js
  packages/yoastseo/src/stringProcessing/addWordboundary.js
  packages/yoastseo/src/stringProcessing/removePunctuation.js
  packages/yoastseo/src/stringProcessing/stripWordBoundaries.js
Labels: changelog: enhancement

#831 Add Arabic external stemmer
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/arabic/stemSpec.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/arabic/stem.js
Labels: changelog: enhancement

#845 P1-160 Unable to dismiss the Meta robots advanced value if there's only one
  packages/components/src/select/Select.js
Labels: changelog: bugfix

#847 Merge Arabic morphology feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/arabic/stemSpec.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/arabic/stem.js
Labels: changelog: non-user-facing

#848 Use value rather than default value so the component can be controlled
  packages/components/src/inputs/TextArea.js
  packages/components/src/inputs/TextInput.js
  packages/components/tests/inputs/TextAreaTest.js
  packages/components/tests/inputs/TextInputTest.js
Labels: changelog: other
