Repository Yoast/javascript, pull requests merged in 2020-12, with the labels that each got.

#955 Lingo 527 implement hungarian passive voice 2
  packages/yoastseo/spec/researches/getPassiveVoiceHungarianSpec.js
  packages/yoastseo/spec/researches/hungarian/passiveVoice/ParticipleSpec.js
  packages/yoastseo/spec/researches/hungarian/passiveVoice/SentencePartSpec.js
  packages/yoastseo/spec/researches/hungarian/passiveVoice/getParticipleSpec.js
  packages/yoastseo/spec/researches/hungarian/passiveVoice/getSentencePartSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsHungarianSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/HungarianParticiple.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/SentencePart.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/auxiliaries.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/determinePassives.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/getParticiples.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/morphologicalPassiveAffixes.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/nonPassivesInVaAndVe.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/odikVerbs.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/participles.js
  packages/yoastseo/src/researches/hungarian/passiveVoice/stopwords.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/determinePassiveSentencePart.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/determineSentencePartIsPassive.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getSentenceParts.js
  packages/yoastseo/src/researches/passiveVoice/periphrastic/getSentencePartsSplitOnStopwords.js
  packages/yoastseo/src/stringProcessing/createRegexFromArray.js
  packages/yoastseo/src/values/SentencePart.js
Labels: changelog: enhancement

#957 Edit Hungarian verbs list
  packages/yoastseo/src/researches/hungarian/passiveVoice/odikVerbs.js
Labels: changelog: non-user-facing

#956 Add specs for getAlttagContent and imageInText helpers
  packages/yoastseo/spec/languageProcessing/helpers/image/getAlttagContentSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/image/imageInTextSpec.js
  packages/yoastseo/spec/stringProcessing/getAlttagContent.js
  packages/yoastseo/src/languageProcessing/helpers/image/getAlttagContent.js
  packages/yoastseo/src/languageProcessing/helpers/image/imageInText.js
Labels: changelog: non-user-facing

#954 Creates unit tests for files inside html helpers
  packages/yoastseo/spec/helpers/htmlSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/findEmptyDivisionsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getSubheadingSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getSubheadingTextsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/matchParagraphsSpec.js
  packages/yoastseo/spec/stringProcessing/matchParagraphsSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/findEmptyDivisions.js
  packages/yoastseo/src/languageProcessing/helpers/html/getSubheadingTexts.js
  packages/yoastseo/src/languageProcessing/helpers/html/html.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
  packages/yoastseo/src/languageProcessing/helpers/html/matchParagraphs.js
  packages/yoastseo/src/languageProcessing/helpers/regex/matchStringWithRegex.js
Labels: changelog: non-user-facing

#958 Move and expand getLanguage unit tests
  packages/yoastseo/spec/languageProcessing/helpers/language/getLanguageSpec.js
Labels: changelog: non-user-facing

#940 Refactor default researcher
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
  packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/researches/urlLength.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
  packages/yoastseo/src/languageProcessing/researches/wordCountInText.js
Labels: changelog: non-user-facing

#964 Configured JSX for the schema-blocks package.
  packages/schema-blocks/.eslintrc
  packages/schema-blocks/tsconfig.json
Labels: changelog: non-user-facing, innovation

#960 Add unit tests for morphology helpers
  packages/yoastseo/spec/languageProcessing/helpers/morphology/baseStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/buildFormRuleSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/buildTopicStemsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/createRulesFromArraysSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/exceptionListHelpersSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/buildFormFromRegexSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/checkExceptionsWithFullFormsSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/exceptionListHelpersSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/buildFormRule.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/createRulesFromArrays.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/exceptionListHelpers.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/determineStem.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/getAdjectiveStem.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/getVerbStem.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/checkExceptionsWithFullForms.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/getStemWordsWithTAndDEnding.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stemModificationHelpers.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stemTOrDFromEndOfWord.js
Labels: changelog: non-user-facing

#959 Add unit tests for link helpers
  packages/yoastseo/spec/languageProcessing/helpers/link/checkNofollowSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/link/getAnchorsFromTextSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/link/linkTypeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/link/getAnchorsFromText.js
  packages/yoastseo/src/languageProcessing/helpers/url/url.js
Labels: changelog: non-user-facing

#966 Add unit tests for prominent words and regex helpers
  packages/yoastseo/spec/languageProcessing/helpers/prominentWords/determineProminentWordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/createRegexFromArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/createRegexFromDoubleArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/createWordRegexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/matchStringWithRegexSpec.js
  packages/yoastseo/src/languageProcessing/helpers/regex/createRegexFromArray.js
  packages/yoastseo/src/languageProcessing/helpers/regex/createRegexFromDoubleArray.js
  packages/yoastseo/src/languageProcessing/helpers/regex/createWordRegex.js
  packages/yoastseo/src/languageProcessing/helpers/regex/matchStringWithRegex.js
Labels: changelog: non-user-facing

#971 Fix clientHeight of undefined error
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: bugfix

#967 Add unit tests for morphology helpers part 2
  packages/yoastseo/spec/languageProcessing/helpers/morphology/findMatchingEndingInArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/flattenSortLengthSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/getAllWordsFromPaperSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/regexHelpersSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/stemHelpersSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/flattenSortLength.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/regexHelpers.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/stemHelpers.js
Labels: changelog: non-user-facing

#968 Add specs for directPrecedenceException and precedenceException files
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/directPrecedenceExceptionSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/precedenceExceptionSpec.js
Labels: changelog: non-user-facing

#970 Add unit tests for sanitize helpers 1
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/mergeListItemsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/parseSynonymsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/quotesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removeNonWordCharacterSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationExceptQuotesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removeSentenceTerminatorsSpec.js
  packages/yoastseo/spec/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/stringProcessing/getSentencesSpec.js
  packages/yoastseo/spec/stringProcessing/removeNonWordCharacterSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/parseSynonyms.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removeNonWordCharacters.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuationExceptQuotes.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removeSentenceTerminators.js
Labels: changelog: non-user-facing

#963 P2-540 additional unit tests for p2 212
  packages/schema-blocks/package.json
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/blocks/BlockDefinitionRepository.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/functions/BlockHelper.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/src/functions/validators/attributeExists.ts
  packages/schema-blocks/src/functions/validators/attributeNotEmpty.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/index.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/tests/core/blocks/BlockInstruction.test.ts
  packages/schema-blocks/tests/functions/innerBlocksHelper.test.ts
  packages/schema-blocks/tests/functions/validators/attributeExists.test.ts
  packages/schema-blocks/tests/functions/validators/attributeNotEmpty.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
  yarn.lock
Labels: changelog: non-user-facing, innovation

#975 P2-576 - Moved schema-blocks CSS to the monorepo.
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/index.ts
Labels: changelog: non-user-facing, innovation

#977 P2 570 unit tests for findselfinvalidatedblocks
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/leaves/blocks/BlockInstructionLeaf.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
Labels: changelog: non-user-facing, innovation

#972 Add Norwegian function words
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/norwegian/functionWords.js
Labels: changelog: enhancement

#976 Add specs for syllable helpers
  packages/yoastseo/spec/helpers/SyllableCountStepSpec.js
  packages/yoastseo/spec/helpers/syllableCountIteratorSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/syllables/DeviationFragmentSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/syllables/countSyllablesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/syllables/syllableCountIteratorSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/syllables/syllableCountStepSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/config/syllablesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/config/syllablesSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countDutchSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countEnglishSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countFrenchSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countGermanSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countItalianSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countPortugueseSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countRussianSpec.js
  packages/yoastseo/spec/stringProcessing/syllables/countSpanishSpec.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/DeviationFragment.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/countSyllables.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountIterator.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountStep.js
  packages/yoastseo/src/languageProcessing/researches/getFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: changelog: non-user-facing

#982 Add sentence length assessment for Turkish
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/src/config/content/combinedConfig.js
  packages/yoastseo/src/config/content/tr.js
Labels: changelog: enhancement

#984 Merge Norwegian feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/norwegian/stemSpec.js
  packages/yoastseo/spec/morphology/norwegian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/norwegian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/norwegian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/norwegian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/hungarian/stem.js
  packages/yoastseo/src/morphology/norwegian/stem.js
  packages/yoastseo/src/researches/norwegian/functionWords.js
Labels: changelog: enhancement

#988 Update readme.md with new assessments for Hungarian and Hebrew
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#978 Add InsightCard component
  packages/components/src/WordOccurrenceInsights.js
  packages/components/src/WordOccurrences.js
  packages/components/src/index.js
  packages/components/src/insights-card/InsightsCard.js
  packages/components/src/insights-card/index.js
  packages/components/src/insights-card/insightscard.css
  packages/components/tests/WordOccurrencesTest.js
  packages/components/tests/__snapshots__/WordOccurrencesTest.js.snap
Labels: changelog: enhancement

#990 Rebase Estimated Reading Time changes from develop
  packages/components/src/WordOccurrenceInsights.js
  packages/components/src/WordOccurrences.js
  packages/components/src/index.js
  packages/components/src/insights-card/InsightsCard.js
  packages/components/src/insights-card/index.js
  packages/components/src/insights-card/insightscard.css
  packages/components/tests/WordOccurrencesTest.js
  packages/components/tests/__snapshots__/WordOccurrencesTest.js.snap
Labels: changelog: enhancement

#993 Enable spellcheck on all replacevar editors.
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
Labels: Package: search-metadata-previews, changelog: enhancement
