Repository Yoast/javascript, pull requests merged in 2020-04, with the labels that each got.

#588 Add specs for verb form looking words ending in -asta, -ista, -ida, and -ido
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
Labels: changelog: non-user-facing

#589 Uncomment specs on stem changing verbs
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
Labels: changelog: non-user-facing

#569 Add CheckboxGroup component
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/checkbox/CheckboxGroup.js
  packages/components/tests/CheckboxGroupTest.js
  packages/components/tests/__snapshots__/CheckboxGroupTest.js.snap
Labels: changelog: enhancement

#581 Create Reactified Toggle Component
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/base/colors.css
  packages/components/src/toggle/Toggle.js
  packages/components/src/toggle/toggle.css
  packages/components/src/toggle/toggle.html
  packages/components/tests/ToggleTest.js
Labels: changelog: non-user-facing

#596 Add specs for Spanish nouns with singular -z and plural -ces
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
Labels: changelog: non-user-facing

#593 Remove global css rules
  packages/components/src/base/index.js
  packages/components/src/base/root.css
  packages/components/src/base/typography.css
  packages/components/src/checkbox/checkbox.css
  packages/components/src/field-group/field-group.css
  packages/components/src/help-icon/help-icon.html
  packages/components/src/inputs/TextArea.js
  packages/components/src/inputs/input.css
  packages/components/src/inputs/input.html
  packages/components/src/modal/modal-mobile-collapsible.html
  packages/components/src/modal/modal-react-tabs.html
  packages/components/src/modal/modal-without-nav.html
  packages/components/src/radiobutton/radiobutton.css
  packages/components/src/select/select.css
Labels: UI change, changelog: bugfix

#600 Fix the text analysis breaking on ying
  packages/yoastseo/spec/morphology/english/determineStemEnglishSpec.js
  packages/yoastseo/src/morphology/english/getVerbStem.js
Labels: changelog: bugfix

#595 LIN 352 Introduce coverage tests for spanish
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/goldStandardStems.json
Labels: changelog: non-user-facing

#599 Enable Spanish morphology
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
Labels: changelog: non-user-facing

#602 Introduce Spanish word form support
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/spanish/stem.js
  packages/yoastseo/src/researches/spanish/functionWords.js
Labels: changelog: enhancement

#584 Create Select components
  apps/components/ReactifiedComponentsWrapper.js
  apps/components/index.html
  packages/components/README.md
  packages/components/internal/ErrorBoundary.js
  packages/components/internal/ErrorWithUrl.js
  packages/components/internal/YoastError.js
  packages/components/src/select/Select.js
  packages/components/src/select/select.css
  packages/components/src/select/select.html
  packages/components/tests/SelectTest.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
Labels: changelog: enhancement

#608 Export the help-icon.css from the index
  packages/components/src/help-icon/index.js
  packages/components/src/index.js
Labels: 0, changelog: bugfix

#609 Add help functions for hidden inputs
  packages/components/src/inputs/TextInput.js
  packages/helpers/src/hiddenInputHelper.js
  packages/helpers/src/index.js
Labels: 1, changelog: enhancement

#606 Add an external stemmer for Russian
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: enhancement

#612 Implement french stemmer
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/french/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#620 2724 update store on image select
  packages/social-metadata-forms/src/redux/actions/formActions.js
  packages/social-metadata-forms/src/redux/reducers/formReducer.js
  packages/social-metadata-forms/tests/redux/reducers/formReducerTest.js
  packages/social-metadata-previews/src/facebook/FacebookImage.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/helpers/determineImageProperties.js
  packages/social-metadata-previews/src/twitter/TwitterImage.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
  packages/social-metadata-previews/tests/facebook/FacebookImageTest.js
  packages/social-metadata-previews/tests/twitter/TwitterImageTest.js
Labels: changelog: bugfix

#610 New component title separator
  packages/components/src/base/utility.css
  packages/components/src/title-separator/title-separator.css
  packages/components/src/title-separator/title-separator.html
Labels: UI change, changelog: non-user-facing

#625 Bump version of node-sass
  packages/yoastseo/package.json
  yarn.lock
Labels: changelog: non-user-facing

#617 Fixed styling select components
  packages/components/src/select/Select.js
  packages/components/src/select/select.css
Labels: UI change, changelog: non-user-facing

#622 Adding stemmer for Portuguese
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/portuguese/stemSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/src/morphology/morphoHelpers/findMatchingEndingInArray.js
  packages/yoastseo/src/morphology/portuguese/stem.js
  packages/yoastseo/src/morphology/spanish/stem.js
Labels: changelog: enhancement

#632 Adds word forms support for French in a beta version
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/french/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: enhancement

#572 Dutch morphology small fixes and clean-up
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/generateParticipleFormSpec.js
  packages/yoastseo/spec/morphology/dutch/stemSpec.js
  packages/yoastseo/spec/morphology/morphoHelpers/exceptionListHelpersSpec.js
  packages/yoastseo/src/morphology/dutch/detectAndStemRegularParticiple.js
  packages/yoastseo/src/morphology/dutch/detectAndStemSuffixes.js
  packages/yoastseo/src/morphology/dutch/determineStem.js
  packages/yoastseo/src/morphology/dutch/generateParticipleForm.js
  packages/yoastseo/src/morphology/dutch/getStemWordsWithTAndDEnding.js
  packages/yoastseo/src/morphology/dutch/stem.js
  packages/yoastseo/src/morphology/dutch/stemModificationHelpers.js
  packages/yoastseo/src/morphology/dutch/stemTOrDFromEndOfWord.js
  packages/yoastseo/src/morphology/morphoHelpers/checkExceptionsWithFullForms.js
  packages/yoastseo/src/morphology/morphoHelpers/stemHelpers.js
  packages/yoastseo/src/researches/dutch/passiveVoice/nonParticiples.js
Labels: changelog: enhancement

#634 Rewire siteName prop to siteUrl and small refactors
  apps/components/FacebookPreviewExample.js
  apps/components/SocialPreviewEditorWrapper.js
  apps/components/TwitterPreviewExample.js
  packages/social-metadata-forms/src/redux/reducers/formReducer.js
  packages/social-metadata-forms/tests/redux/reducers/formReducerTest.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/facebook/FacebookSiteAndAuthorNames.js
  packages/social-metadata-previews/src/facebook/FacebookSiteName.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
  packages/social-metadata-previews/src/twitter/TwitterSiteUrl.js
  packages/social-metadata-previews/tests/facebook/FacebookPreviewTest.js
  packages/social-metadata-previews/tests/facebook/FacebookSiteAndAuthorNamesTest.js
  packages/social-metadata-previews/tests/facebook/FacebookSiteNameTest.js
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookPreviewTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookSiteAndAuthorNamesTest.js.snap
  packages/social-metadata-previews/tests/facebook/__snapshots__/FacebookSiteNameTest.js.snap
  packages/social-metadata-previews/tests/twitter/TwitterPreviewTest.js
  packages/social-metadata-previews/tests/twitter/TwitterSiteNameTest.js
  packages/social-metadata-previews/tests/twitter/__snapshots__/TwitterSiteNameTest.js.snap
Labels: changelog: non-user-facing

#635 Changed morphology version number to v5
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#639 Show HelpIcon only if link is provided to FieldGroup
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/help-icon/HelpIcon.js
  packages/components/tests/__snapshots__/CheckboxGroupTest.js.snap
  packages/components/tests/__snapshots__/SelectTest.js.snap
  packages/components/tests/inputs/TextAreaTest.js
  packages/components/tests/inputs/TextInputTest.js
Labels: Package: components, changelog: enhancement

#636 add french to the list of supported languages
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
Labels: changelog: enhancement

#640 Add colors and icons used in plugin
  packages/components/src/base/colors.css
  packages/components/src/base/icons.css
  packages/components/src/base/typography.css
Labels: UI change, changelog: non-user-facing

#641 Use morphology data in French stemmer
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/morphology/french/stem.js
Labels: changelog: non-user-facing

#643 Export components for advanced tab from root
  packages/components/src/inputs/index.js
  packages/components/src/radiobutton/index.js
  packages/components/src/select/index.js
Labels: Package: components, changelog: bugfix

#645 Move internals folder within src folder
  packages/components/src/internal/ErrorBoundary.js
  packages/components/src/internal/ErrorWithUrl.js
  packages/components/src/internal/YoastError.js
  packages/components/src/select/Select.js
Labels: changelog: non-user-facing

#648 Add prop to SocialPreviewEditor for replaceVars
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: enhancement

#624 Add Indonesian stemmer
  packages/yoastseo/package.json
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/morphology/indonesian/helpers.js
  packages/yoastseo/src/morphology/indonesian/stem.js
Labels: changelog: enhancement

#650 Create the DataModel component
  .gitignore
  apps/components/ReactifiedComponentsWrapper.js
  apps/components/WordOccurrencesWrapper.js
  packages/components/src/WordOccurrences.js
  packages/components/src/data-model/DataModel.js
  packages/components/src/data-model/index.js
  packages/components/tests/DataModelTest.js
  packages/components/tests/__snapshots__/DataModelTest.js.snap
  packages/components/tests/__snapshots__/WordOccurrencesTest.js.snap
Labels: changelog: enhancement

#649 Fro 10 update toggle css
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/toggle/Toggle.js
  packages/components/src/toggle/toggle.css
  packages/components/src/toggle/toggle.html
Labels: changelog: enhancement, changelog: other

#644 Move Russian stemming data to morphology data file
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper3.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/russian/stem.js
Labels: changelog: non-user-facing

#637 Select text overflow fix
  packages/components/src/select/select.css
Labels: UI change, changelog: non-user-facing

#651 Move Italian stemming data to morphology data file
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/italian/stem.js
  packages/yoastseo/src/morphology/morphoHelpers/createRulesFromMorphologyData.js
Labels: changelog: non-user-facing

#652 Provide the correct props to the components
  packages/social-metadata-forms/src/ImageSelect.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
Labels: changelog: bugfix
