Repository Yoast/javascript, pull requests merged in 2020-01, with the labels that each got.

#438 Rename Snippet preview to Google preview in i18n string
  packages/yoastseo/src/snippetPreview.js
Labels: changelog: non-user-facing

#430 Refactor html tree adapter
  packages/yoastseo/spec/parsedPaper/build/tree/buildTreeFromYamlSpec.js
  packages/yoastseo/spec/parsedPaper/build/tree/cleanup/calculateTextIndicesSpec.js
  packages/yoastseo/spec/parsedPaper/build/tree/html/buildTreeSpec.js
  packages/yoastseo/spec/parsedPaper/build/tree/html/treeAdapterSpec.js
  packages/yoastseo/spec/parsedPaper/research/researches/HeadingsSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/FormattingElementSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/HeadingSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/IgnoredSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/ListItemSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/ListSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/NodeSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/ParagraphSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/StructuredNodeSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/nodes/WhitespaceSpec.js
  packages/yoastseo/spec/specHelpers/buildTreeFromYaml.js
  packages/yoastseo/src/parsedPaper/build/tree/cleanup/calculateTextIndices.js
  packages/yoastseo/src/parsedPaper/build/tree/cleanup/postParsing.js
  packages/yoastseo/src/parsedPaper/build/tree/html/HTMLTreeConverter.js
  packages/yoastseo/src/parsedPaper/build/tree/html/TreeAdapter.js
  packages/yoastseo/src/parsedPaper/build/tree/html/buildTree.js
  packages/yoastseo/src/parsedPaper/build/tree/html/htmlConstants.js
  packages/yoastseo/src/parsedPaper/structure/tree/FormattingElement.js
  packages/yoastseo/src/parsedPaper/structure/tree/SourceCodeLocation.js
  packages/yoastseo/src/parsedPaper/structure/tree/TextContainer.js
  packages/yoastseo/src/parsedPaper/structure/tree/index.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/Heading.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/Ignored.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/LeafNode.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/List.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/ListItem.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/Node.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/Paragraph.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/StructuredNode.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/Whitespace.js
  packages/yoastseo/src/parsedPaper/structure/tree/nodes/index.js
Labels: changelog: non-user-facing

#434 Add include merged tags option to the lerna config
  lerna.json
Labels: 8, changelog: non-user-facing, tooling

#439 Change tree builer error output to the logger instead of the console
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#450 426 create link statistics research
  packages/yoastseo/spec/parsedPaper/research/researches/LinkStatisticsSpec.js
  packages/yoastseo/spec/parsedPaper/research/researches/ResearchSpec.js
  packages/yoastseo/src/parsedPaper/research/index.js
  packages/yoastseo/src/parsedPaper/research/researches/Headings.js
  packages/yoastseo/src/parsedPaper/research/researches/LinkStatistics.js
  packages/yoastseo/src/parsedPaper/research/researches/Research.js
  packages/yoastseo/src/parsedPaper/structure/tree/FormattingElement.js
Labels: changelog: non-user-facing

#441 Errors during the tree building process get logged by console.error again
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#451 Ignore whitespace only implicit paragraphs
  packages/yoastseo/spec/parsedPaper/build/tree/html/buildTreeSpec.js
  packages/yoastseo/src/parsedPaper/build/tree/html/HTMLTreeConverter.js
  packages/yoastseo/src/parsedPaper/build/tree/html/buildTree.js
  packages/yoastseo/src/parsedPaper/build/tree/html/htmlConstants.js
Labels: 1, changelog: non-user-facing

#449 Fix grunt get-premium-configuration switching
  packages/yoastseo/grunt/config/shell.js
Labels: changelog: non-user-facing

#455 LIN-128 Adapt existing analysis methods to work with metadata
  packages/yoastseo/spec/parsedPaper/assess/assessments/AssessmentSpec.js
  packages/yoastseo/src/parsedPaper/assess/assessments/Assessment.js
  packages/yoastseo/src/parsedPaper/assess/assessments/index.js
  packages/yoastseo/src/parsedPaper/build/tree/TreeBuilder.js
  packages/yoastseo/src/parsedPaper/research/TreeResearcher.js
Labels: changelog: non-user-facing

#459 LIN-80 Create sentence parser
  packages/yoastseo/grunt/config/eslint.js
  packages/yoastseo/spec/parsedPaper/build/linguisticParsing/parseTextSpec.js
  packages/yoastseo/spec/parsedPaper/structure/tree/TextContainerSpec.js
  packages/yoastseo/src/parsedPaper/build/linguisticParsing/Sentence.js
  packages/yoastseo/src/parsedPaper/build/linguisticParsing/SentenceTokenizer.js
  packages/yoastseo/src/parsedPaper/build/linguisticParsing/parseText.js
  packages/yoastseo/src/parsedPaper/structure/tree/TextContainer.js
Labels: changelog: non-user-facing

#460 LIN-152 Disable everything tree-related in the web worker and distribution
  packages/yoastseo/grunt/config/babel.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#478 Update draftJS in components and search-metadata-previews
  packages/search-metadata-previews/package.json
  packages/yoast-components/package.json
  yarn.lock
Labels: changelog: non-user-facing
