Repository Yoast/javascript, pull requests merged in 2020-09, with the labels that each got.

#849 Implement Farsi affixes to be ignored in keyphrase recognition
  packages/yoastseo/spec/morphology/farsi/createBasicWordFormsFarsiSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/helpers/getBasicWordForms.js
  packages/yoastseo/src/morphology/farsi/createBasicWordForms.js
  packages/yoastseo/src/morphology/morphoHelpers/regexHelpers.js
Labels: changelog: enhancement

#846 Add function words assessment for Farsi
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/arabic/functionWords.js
  packages/yoastseo/src/researches/farsi/functionWords.js
Labels: changelog: enhancement

#483 Update README.md
  packages/yoastseo/README.md
Labels: community-patch

#851 Adjust MultiSelect to enable SingleSelect
  packages/components/src/select/Select.js
  packages/components/src/select/index.js
Labels: changelog: non-user-facing

#850 Add Swedish external stemmer
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper2.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/swedish/stemSpec.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/swedish/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/swedish/stem.js
Labels: changelog: enhancement

#858 Merge Farsi feature branch
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/arabic/functionWords.js
  packages/yoastseo/src/researches/farsi/functionWords.js
Labels: changelog: non-user-facing

#860 Merge Farsi keyphrase recognition feature branch
  packages/yoastseo/spec/morphology/farsi/createBasicWordFormsFarsiSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/helpers/getBasicWordForms.js
  packages/yoastseo/src/morphology/farsi/createBasicWordForms.js
  packages/yoastseo/src/morphology/morphoHelpers/regexHelpers.js
Labels: changelog: non-user-facing

#862 QAK-2247 Fix the Arabic passive voice assessment bug
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/researches/getPassiveVoiceArabicSpec.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: non-user-facing

#863 P1-181 Add id to the multiselect input
  packages/components/src/select/Select.js
Labels: changelog: other

#857 P3-170 Changes and additions needed for SEMrush integration feature
  packages/components/src/index.js
  packages/components/src/select/Select.js
  packages/components/src/select/index.js
  packages/components/src/select/select.css
  packages/components/src/tables/index.js
  packages/yoast-components/composites/Plugin/Shared/components/KeywordInput.js
  packages/yoast-components/composites/Plugin/Shared/tests/KeywordInputTest.js
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
  packages/yoast-components/package.json
Labels: changelog: enhancement

#868 P3 172 p3 175 fix semrush country selector styling
  packages/components/src/select/select.css
Labels: changelog: non-user-facing

#867 Update rules for non-passives and exception list
  packages/yoastseo/spec/researches/getPassiveVoiceIndonesianSpec.js
  packages/yoastseo/src/researches/indonesian/passiveVoice/nonPassiveVerbsStartingDi.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
Labels: changelog: enhancement

#872 Improve edit button RTL styling
  packages/components/src/button/buttons.css
Labels: changelog: bugfix

#871 Temporarily export new Button as NewButton to avoid conflicts
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/button/index.js
  packages/components/tests/button/ButtonsTest.js
Labels: changelog: bugfix

#866 P1-190 add ids
  packages/components/src/select/Select.js
  packages/helpers/src/index.js
  packages/helpers/src/join.js
  packages/helpers/tests/joinTest.js
  packages/search-metadata-previews/src/snippet-editor/ModeSwitcher.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/social-metadata-forms/src/ImageSelect.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-forms/tests/ImageSelectTest.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: enhancement
