Repository Yoast/javascript, pull requests merged in 2020-11, with the labels that each got.

#913 Removes the configuration wizard imports- and exports from the yoast-components package and deprecates the exports.
  packages/yoast-components/index.js
Labels: changelog: bugfix

#904 Refactor keyword density assessment
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/_default/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/ar/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/de/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/es/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/fr/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/id/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/it/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/nl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/pl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/pt/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/ru/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/researches/base/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/researches/getKeywordDensity.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
Labels: changelog: non-user-facing

#901 Audit yoastseo/src/helpers
  packages/yoastseo/spec/helpers/htmlSpec.js
  packages/yoastseo/spec/helpers/inRangeSpec.js
  packages/yoastseo/spec/helpers/isValueTooLongSpec.js
  packages/yoastseo/src/.DS_Store
  packages/yoastseo/src/helpers/_todo/index.js
  packages/yoastseo/src/helpers/gini.js
  packages/yoastseo/src/helpers/isValueTooLong.js
  packages/yoastseo/src/languageProcessing/helpers/html/html.js
  packages/yoastseo/src/languageProcessing/helpers/html/matchParagraphs.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripHTMLTags.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/researches/h1s.js
  packages/yoastseo/src/scoring/assessments/readability/paragraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInDescriptionAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/subheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextImagesAssessment.js
  packages/yoastseo/src/scoring/helpers/assessments/checkForTooLongSentences.js
  packages/yoastseo/src/scoring/helpers/assessments/inRange.js
  packages/yoastseo/src/scoring/helpers/assessments/keyphraseLengthFactor.js
  packages/yoastseo/src/scoring/helpers/assessments/recommendedKeywordCount.js
Labels: changelog: non-user-facing

#909 Removes yoastseo/src/config/config.js
  packages/yoastseo/src/app.js
  packages/yoastseo/src/config/config.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/snippetPreview/snippetPreview.js
Labels: changelog: non-user-facing

#894 P2-366 Merge Feature/schema blocks into develop
  README.md
  packages/configuration-wizard/package.json
  packages/schema-blocks/.eslintrc
  packages/schema-blocks/.gitignore
  packages/schema-blocks/.npmignore
  packages/schema-blocks/package.json
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/Leaf.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/blocks/BlockLeaf.ts
  packages/schema-blocks/src/core/schema/SchemaDefinition.ts
  packages/schema-blocks/src/core/schema/SchemaInstruction.ts
  packages/schema-blocks/src/core/schema/SchemaLeaf.ts
  packages/schema-blocks/src/functions/blocks.ts
  packages/schema-blocks/src/functions/blocks/parse.ts
  packages/schema-blocks/src/functions/gutenberg/block.ts
  packages/schema-blocks/src/functions/gutenberg/filter.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/html.ts
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/src/functions/schema/parse.ts
  packages/schema-blocks/src/functions/select.ts
  packages/schema-blocks/src/functions/separator.ts
  packages/schema-blocks/src/functions/tokenize.ts
  packages/schema-blocks/src/index.ts
  packages/schema-blocks/src/instructions/blocks/Block.ts
  packages/schema-blocks/src/instructions/blocks/ClassName.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/RichText.ts
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/src/instructions/blocks/SidebarInput.ts
  packages/schema-blocks/src/instructions/blocks/SidebarSelect.ts
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
  packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
  packages/schema-blocks/src/instructions/blocks/abstract/SidebarBase.ts
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/instructions/index.ts
  packages/schema-blocks/src/instructions/schema/Attribute.ts
  packages/schema-blocks/src/instructions/schema/BlockId.ts
  packages/schema-blocks/src/instructions/schema/HTML.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocks.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksHTML.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksID.ts
  packages/schema-blocks/src/instructions/schema/List.ts
  packages/schema-blocks/src/instructions/schema/Permalink.ts
  packages/schema-blocks/src/instructions/schema/Schema.ts
  packages/schema-blocks/src/instructions/schema/index.ts
  packages/schema-blocks/src/leaves/blocks/BlockElementLeaf.ts
  packages/schema-blocks/src/leaves/blocks/BlockInstructionLeaf.ts
  packages/schema-blocks/src/leaves/blocks/BlockRootLeaf.ts
  packages/schema-blocks/src/leaves/blocks/BlockTextLeaf.ts
  packages/schema-blocks/src/leaves/schema/SchemaArrayLeaf.ts
  packages/schema-blocks/src/leaves/schema/SchemaConstantLeaf.ts
  packages/schema-blocks/src/leaves/schema/SchemaInstructionLeaf.ts
  packages/schema-blocks/src/leaves/schema/SchemaInterpolatedLeaf.ts
  packages/schema-blocks/src/leaves/schema/SchemaObjectLeaf.ts
  packages/schema-blocks/tsconfig.json
  yarn.lock
Labels: Package: schema-blocks

#917 Remove unnecessary dependency
  package.json
Labels: changelog: non-user-facing

#916 P2-354 Set up typescript tests for the `schema-blocks` package.
  packages/schema-blocks/README.md
  packages/schema-blocks/jest.config.js
  packages/schema-blocks/package.json
  packages/schema-blocks/tests/functions/select.test.ts
  yarn.lock
Labels: changelog: non-user-facing

#915 Refactor get keyword density and keyphrase length researches
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/researches/keyphraseLength.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
Labels: changelog: non-user-facing

#919 Refactor Arabic researcher
  packages/yoastseo/spec/morphology/arabic/createBasicWordFormsArabicSpec.js
  packages/yoastseo/spec/morphology/arabic/stemSpec.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/ar/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ar/config/internal/passiveVerbsWithLongVowel.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/createBasicWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/ar/researches/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#923 P2-213 add property validation
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/functions/validators/attributeExists.ts
  packages/schema-blocks/src/functions/validators/attributeNotEmpty.ts
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/src/instructions/blocks/SidebarInput.ts
  packages/schema-blocks/src/instructions/blocks/SidebarSelect.ts
  packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
  packages/schema-blocks/src/instructions/blocks/abstract/SidebarBase.ts
  packages/schema-blocks/tests/core/blocks/BlockInstruction.test.ts
  packages/schema-blocks/tests/functions/validators/attributeExists.test.ts
  packages/schema-blocks/tests/functions/validators/attributeNotEmpty.test.ts
Labels: changelog: enhancement

#924 Refactor Hungarian Researcher
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/hu/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/hu/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/hu/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
Labels: changelog: non-user-facing

#921 Refactor farsi researcher
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fa/helpers/createBasicWordForms.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/fa/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/researches/getWordForms.js
Labels: changelog: non-user-facing

#922 Refactor Hebrew Researcher
  packages/yoastseo/src/languageProcessing/languages/he/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/he/helpers/createBasicWordForms.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/he/researches/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#927 Refactor Catalan researcher
  packages/yoastseo/src/languageProcessing/languages/ca/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ca/researches/getWordForms.js
Labels: changelog: non-user-facing

#925 Refactor Indonesian researcher
  packages/yoastseo/spec/morphology/indonesian/stemSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/id/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/id/config/internal/nonPassiveVerbsStartingDi.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stemHelpers.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/id/researches/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#926 Refactor Swedish researcher
  packages/yoastseo/src/languageProcessing/languages/sv/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/internal/passiveVerbs.js
  packages/yoastseo/src/languageProcessing/languages/sv/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/sv/researches/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#928 Refactor Polish researcher
  packages/yoastseo/spec/morphology/polish/stemSpec.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/nonDirectParticiplePrecedenceException.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/en/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/pl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/internal/auxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/internal/participles.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/pl/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/pl/values/PolishParticiple.js
  packages/yoastseo/src/languageProcessing/languages/pl/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoice.js
Labels: changelog: non-user-facing

#918 Refactor flesch reading research
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/en/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/researches/getFleschReadingScore.js
  packages/yoastseo/src/scoring/assessments/readability/fleschReadingEaseAssessment.js
Labels: changelog: non-user-facing

#931 Refactor German Researcher
  packages/yoastseo/spec/morphology/german/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/morphology/german/determineStemSpec.js
  packages/yoastseo/spec/morphology/german/stemSpec.js
  packages/yoastseo/src/languageProcessing/languages/de/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/de/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/exceptionsParticiplesActive.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/passiveVoiceIrregulars.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/passiveVoiceRegex.js
  packages/yoastseo/src/languageProcessing/languages/de/config/passiveVoice/determinePassives.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/detectAndStemRegularParticiple.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/determineStem.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/de/morphology/helpers.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/de/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/de/values/GermanParticiple.js
  packages/yoastseo/src/languageProcessing/languages/de/values/SentencePart.js
Labels: changelog: non-user-facing

#933 Add additional languages to reading time helper
  packages/yoastseo/spec/researches/readingTimeSpec.js
  packages/yoastseo/src/researches/readingTime.js
Labels: changelog: non-user-facing

#932 Refactor Spanish researcher
  packages/yoastseo/spec/morphology/spanish/stemSpec.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/es/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/es/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/es/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/es/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/es/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/es/values/SpanishParticiple.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInPageTitle.js
Labels: changelog: non-user-facing

#935 Improve Arabic text analysis by stemming prefix combinations
  packages/yoastseo/spec/morphology/arabic/createBasicWordFormsArabicSpec.js
  packages/yoastseo/spec/researches/getWordFormsSpec.js
  packages/yoastseo/src/morphology/arabic/createBasicWordForms.js
Labels: changelog: enhancement

#934 Refactor French Researcher
  packages/yoastseo/spec/morphology/french/stemSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/matchRegularParticiples.js
  packages/yoastseo/src/languageProcessing/languages/fr/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/exceptionsParticiplesActive.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/passiveVoiceIrregulars.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/passiveVoice/auxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/stopwords.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/fr/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/fr/values/FrenchParticiple.js
  packages/yoastseo/src/languageProcessing/languages/fr/values/SentencePart.js
Labels: changelog: non-user-facing

#936 Refactor Italian researcher
  packages/yoastseo/spec/morphology/italian/stemSpec.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/italian/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/it/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/it/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/it/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/it/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/it/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/it/config/passiveVoice/auxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/it/config/passiveVoice/participles.js
  packages/yoastseo/src/languageProcessing/languages/it/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/it/config/stopwords.js
  packages/yoastseo/src/languageProcessing/languages/it/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/it/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/it/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/it/values/ItalianParticiple.js
  packages/yoastseo/src/languageProcessing/languages/it/values/SentencePart.js
Labels: changelog: non-user-facing

#937 Refactor Dutch researcher
  packages/yoastseo/spec/morphology/dutch/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/morphology/dutch/determineStemSpec.js
  packages/yoastseo/spec/morphology/dutch/getStemWordsWithTAndDEndingSpecs.js
  packages/yoastseo/spec/morphology/dutch/stemSpec.js
  packages/yoastseo/spec/morphology/dutch/stemTOrDFromEndOfWordSpec.js
  packages/yoastseo/src/languageProcessing/languages/nl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/internal/nonParticiples.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/internal/passiveVoiceIrregulars.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/passiveVoice/irregulars.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/passiveVoice/nonParticiples.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/stopwords.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/detectAndStemRegularParticiple.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/detectAndStemSuffixes.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/determineStem.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/getStemWordsWithTAndDEnding.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stemModificationHelpers.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stemTOrDFromEndOfWord.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/nl/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/nl/values/DutchParticiple.js
  packages/yoastseo/src/languageProcessing/languages/nl/values/SentencePart.js
Labels: changelog: non-user-facing

#938 Refactor Portuguese Researcher
  packages/yoastseo/spec/morphology/portuguese/stemSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/pt/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/passiveVoice/auxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/passiveVoice/participles.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/stopwords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/stopWordsInKeyword.js
  packages/yoastseo/src/languageProcessing/languages/pt/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/languages/pt/values/PortugueseParticiple.js
  packages/yoastseo/src/languageProcessing/languages/pt/values/SentencePart.js
Labels: changelog: non-user-facing

#939 Refactor Russian Researcher
  packages/yoastseo/spec/morphology/russian/stemSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/generateStems.js
  packages/yoastseo/src/languageProcessing/languages/ru/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/internal/participlesShortenedList.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/calculateFleschReadingScore.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/calculateFleschReading.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/findTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getProminentWordsForInternalLinking.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/ru/researches/matchKeywordInSubheadings.js
Labels: changelog: non-user-facing

#930 LINGO-531 Add sentence beginning assessment for Hungarian
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/researches/hungarian/firstWordExceptions.js
Labels: changelog: enhancement

#941 Add sentence length assessment for Hungarian
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
Labels: changelog: non-user-facing

#914 LINGO-467 Edit Hungarian transition words
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/researches/hungarian/transitionWords.js
  packages/yoastseo/src/researches/hungarian/twoPartTransitionWords.js
  packages/yoastseo/src/stringProcessing/createRegexFromDoubleArray.js
Labels: changelog: enhancement

#942 Add hungarian function words
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/farsi/functionWords.js
  packages/yoastseo/src/researches/hungarian/functionWords.js
Labels: changelog: enhancement

#947 P1-261 Capture anchor tags with whitespace inside
  packages/yoastseo/spec/stringProcessing/getAnchorsFromTextSpec.js
  packages/yoastseo/src/stringProcessing/getAnchorsFromText.js
Labels: changelog: bugfix

#944 Add support for templates to inner blocks
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/src/functions/tokenize.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/tests/functions/process.test.ts
  packages/schema-blocks/tests/functions/tokenize.test.ts
  packages/schema-blocks/tests/functions/tokenize.testdata.ts
  packages/schema-blocks/tests/instructions/Innerblocks.test.ts
  packages/schema-blocks/tests/matchMedia.mock
Labels: changelog: non-user-facing, innovation

#943 Remove locale from Sentence and SentencePart objects
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSplitOnStopwords.js
  packages/yoastseo/src/languageProcessing/languages/de/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/en/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/es/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/fr/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/it/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/nl/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/pl/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/pt/values/SentencePart.js
  packages/yoastseo/src/values/Sentence.js
  packages/yoastseo/src/values/SentencePart.js
Labels: changelog: non-user-facing

#946 P2 212 add innerblocks validation
  packages/schema-blocks/package.json
  packages/schema-blocks/src/functions/blocks/recurseOverBlocks.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/dto/InvalidBlock.ts
  packages/schema-blocks/src/instructions/blocks/dto/RequiredBlock.ts
  packages/schema-blocks/src/instructions/blocks/dto/index.ts
  packages/schema-blocks/src/instructions/blocks/enums/InvalidBlockReason.ts
  packages/schema-blocks/src/instructions/blocks/enums/RequiredBlockOption.ts
  packages/schema-blocks/src/instructions/blocks/enums/index.ts
  packages/schema-blocks/tests/functions/innerBlocksHelper.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
Labels: changelog: non-user-facing, innovation

#948 LINGO-349 Add Hungarian stemmer
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/hungarian/stem.js
Labels: changelog: enhancement

#950 LINGO-548 Merge Hungarian feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemSpec.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/hungarian/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/hungarian/stem.js
  packages/yoastseo/src/researches/farsi/functionWords.js
  packages/yoastseo/src/researches/hungarian/firstWordExceptions.js
  packages/yoastseo/src/researches/hungarian/functionWords.js
  packages/yoastseo/src/researches/hungarian/transitionWords.js
  packages/yoastseo/src/researches/hungarian/twoPartTransitionWords.js
  packages/yoastseo/src/stringProcessing/createRegexFromDoubleArray.js
Labels: changelog: enhancement
