Repository Yoast/javascript, pull requests merged in 2021-04, with the labels that each got.

#1140 Externalize imports for Czech files
  packages/yoastseo/src/languageProcessing/languages/cs/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/CzechParticiple.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/SentencePart.js
Labels: changelog: non-user-facing

#1135 P2 686 render svg icon
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
Labels: changelog: non-user-facing, innovation

#1141 Added typings entry in schema-blocks package.json
  packages/schema-blocks/package.json
Labels: changelog: non-user-facing, tooling

#1139 P2-775 Fixes some React keys in the schema blocks React components
  packages/schema-blocks/src/blocks/BlockSuggestions.tsx
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
Labels: changelog: non-user-facing, innovation

#1124 Only output Schema when the checks for required blocks are OK
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/validators/getAllDescendantIssues.ts
  packages/schema-blocks/src/functions/validators/index.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/functions/validators/isValidResult.ts
  packages/schema-blocks/tests/core/Definition.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
  packages/schema-blocks/tests/functions/validators/validateMany.test.ts
Labels: changelog: bugfix, innovation

#1121 P1-323 Fix keyboard trap in replacement variable editors
  packages/replacement-variable-editor/package.json
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/helpers/positionSuggestions.js
  packages/replacement-variable-editor/tests/positionSuggestionsTest.js
  packages/search-metadata-previews/package.json
  packages/yoast-components/package.json
  yarn.lock
Labels: changelog: bugfix

#1145 P2-837 Refactor block validation enum
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/validators/index.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/functions/validators/isValidResult.ts
  packages/schema-blocks/src/functions/validators/validateMany.ts
  packages/schema-blocks/src/functions/validators/validateResults.ts
  packages/schema-blocks/src/instructions/blocks/Title.tsx
Labels: changelog: enhancement, innovation

#1113 Merge Czech feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/README.md
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/languageProcessing/languages/cs/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/values/CzechParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoice/getPassiveVoiceCzechSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  packages/yoastseo/src/languageProcessing/languages/cs/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/internal/passiveVoiceEndings.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/CzechParticiple.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/SentencePart.js
Labels: changelog: enhancement

#1126 Add SentenceNew and Clause classes and their specs
  packages/yoastseo/spec/values/ClauseSpec.js
  packages/yoastseo/spec/values/SentenceNewSpec.js
  packages/yoastseo/src/values/Clause.js
  packages/yoastseo/src/values/SentenceNew.js
Labels: changelog: non-user-facing

#1143 Show the variation picker again when its inner-blocks are removed
  packages/schema-blocks/src/functions/presenters/VariationPickerPresenter.tsx
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
Labels: changelog: enhancement

#1136 Connected Redux store with React to make sure the components update whenever the store changes.
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/tests/functions/presenters/BlockSuggestions.test.ts
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestions.test.ts.snap
Labels: changelog: bugfix

#1149 Change the color of the analysis messages from grey to black
  packages/schema-blocks/css/schema-blocks.css
Labels: UI change, changelog: enhancement

#1118 P1 345 woo shopping data in google preview
  apps/components/ComponentsExample.js
  packages/components/src/index.js
  packages/components/src/star-rating/StarRating.js
  packages/components/src/star-rating/index.js
  packages/components/src/star-rating/star-rating.css
  packages/search-metadata-previews/src/index.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
  packages/search-metadata-previews/src/snippet-preview/ProductDataMobile.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/SnippetEditorTest.js
  packages/search-metadata-previews/tests/SnippetPreviewTest.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: changelog: enhancement, innovation

#1152 Added default-tag attribute to variable rich text instruction
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
Labels: changelog: enhancement, innovation

#1150 Replace OK by a green checkmark
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestions.test.ts.snap
Labels: UI change, changelog: enhancement, innovation

#1153 Sets the textdomain to the right one
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
Labels: changelog: non-user-facing

#1156 Watch the post title for validation
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/instructions/blocks/Title.tsx
Labels: changelog: enhancement, innovation

#1142 P2 807 variation picker validation
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/core/validation/index.ts
  packages/schema-blocks/src/functions/gutenberg/block.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/functions/validators/validateMany.ts
  packages/schema-blocks/src/instructions/blocks/InheritSidebar.tsx
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
  packages/schema-blocks/tests/core/blocks/BlockInstruction.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
  packages/schema-blocks/tests/functions/validators/validateMany.test.ts
Labels: changelog: enhancement, innovation

#1154 Improve structure of passive voice helpers and of values related to language processing
  apps/components/WordOccurrencesWrapper.js
  packages/components/tests/WordOccurrencesTest.js
  packages/yoastseo/index.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/directPrecedenceExceptionSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getSentencePartsSplitOnStopwordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getClausesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/precedenceExceptionSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/prominentWords/determineProminentWordsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/values/ClauseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInsightsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/spec/languageProcessing/values/ClauseSpec.js
  packages/yoastseo/spec/languageProcessing/values/ProminentWordSpec.js
  packages/yoastseo/spec/languageProcessing/values/SentenceNewSpec.js
  packages/yoastseo/spec/worker/transporter/parseSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/directPrecedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWords.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getSentencePartsSplitOnStopwords.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/precedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/prominentWords/determineProminentWords.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/languages/en/values/Clause.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoiceResult.js
  packages/yoastseo/src/languageProcessing/values/Clause.js
  packages/yoastseo/src/languageProcessing/values/ProminentWord.js
  packages/yoastseo/src/languageProcessing/values/SentenceNew.js
  packages/yoastseo/src/languageProcessing/values/index.js
  packages/yoastseo/src/values/index.js
  packages/yoastseo/src/worker/transporter/parse.js
Labels: changelog: non-user-facing

#1160 P1-475 revert draft-js upgrade
  packages/replacement-variable-editor/package.json
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/helpers/positionSuggestions.js
  packages/replacement-variable-editor/tests/positionSuggestionsTest.js
  yarn.lock
Labels: changelog: non-user-facing

#1158 Add 'new' badge component
  packages/components/src/index.js
  packages/components/src/new-badge/NewBadge.js
  packages/components/src/new-badge/index.js
  packages/components/src/new-badge/new-badge.css
Labels: changelog: non-user-facing

#1157 Injects the sidebar into core blocks
  packages/schema-blocks/src/functions/blocks/getParentSidebar.tsx
  packages/schema-blocks/src/functions/gutenberg/inject-sidebar.tsx
  packages/schema-blocks/src/functions/initialize.ts
  packages/schema-blocks/tests/functions/blocks/__snapshots__/getParentSidebar.test.ts.snap
  packages/schema-blocks/tests/functions/blocks/getParentSidebar.test.ts
Labels: changelog: enhancement, innovation

#1159 Fixed analysis conclusion, based on recent changes in the block validation.
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
Labels: changelog: bugfix, innovation

#1162 P2-860 Fixes a console warning due to an invalid key property in the VariationPickerPresenter.
  packages/schema-blocks/src/functions/presenters/VariationPickerPresenter.tsx
Labels: changelog: bugfix

#1163 Added warning block to list of blocks who should inherit the sidebar
  packages/schema-blocks/src/functions/initialize.ts
Labels: changelog: bugfix

#1155 P2-814 Implement appender according to design
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/functions/presenters/BlockAppender.tsx
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/tests/functions/presenters/BlockAppender.test.ts
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockAppender.test.ts.snap
Labels: UI change, changelog: other, innovation

#1165 Add header with link to the sidebar and improve the sidebar's styling
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestions.test.ts.snap
Labels: UI change, changelog: enhancement, innovation

#1166 P2-781 Remove warning blocks when they do not apply anymore
  packages/schema-blocks/src/blocks/warning-block/edit.ts
  packages/schema-blocks/src/blocks/warning-block/index.ts
  packages/schema-blocks/src/blocks/warning-block/warningBlockAttributes.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/removeObsoleteWarnings.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/removeObsoleteWarnings.test.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
Labels: changelog: other, innovation

#1164 Check if block is active before activating the sidebar
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
Labels: changelog: bugfix, innovation

#1169 P2-853 Heading instruction
  packages/schema-blocks/src/functions/presenters/HeadingLevelDropdown.tsx
  packages/schema-blocks/src/functions/presenters/HeadingLevelIcon.tsx
  packages/schema-blocks/src/instructions/blocks/Date.tsx
  packages/schema-blocks/src/instructions/blocks/Heading.tsx
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
  packages/schema-blocks/src/instructions/blocks/index.ts
Labels: changelog: enhancement

#1147 Add "New" badge component for global social templates
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/image-select/ImageSelect.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
Labels: changelog: non-user-facing

#1172 P2-861 - Made sure that no innerblocks instruction sidebar is rendered when no required or recommended blocks are set.
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
Labels: changelog: bugfix

#1171 Exports the instances needed which are needed in premium
  packages/schema-blocks/src/index.ts
Labels: changelog: non-user-facing, innovation

#1170 Always wrap the inherited sidebar in a PanelBody component.
  packages/schema-blocks/src/functions/blocks/getParentSidebar.tsx
  packages/schema-blocks/tests/functions/blocks/__snapshots__/getParentSidebar.test.ts.snap
Labels: changelog: bugfix

#1173 Passive refactor clean up
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/determineSentencePartIsPassiveSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getSentencePartsSplitOnStopwordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoice/getPassiveVoiceFrenchSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoice/getPassiveVoicePolishSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoice/getPassiveVoiceSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultArabicSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultCzechSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultDutchSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultEnglishSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultFrenchSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultGermanSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultHebrewSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultHungarianSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultIndonesianSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultItalianSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultPolishSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultPortugueseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultRussianSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultSpanishSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultSwedishSpec.js
  packages/yoastseo/spec/languageProcessing/values/SentenceSpec.js
  packages/yoastseo/spec/values/ParticipleSpec.js
  packages/yoastseo/spec/values/SentenceSpec.js
  packages/yoastseo/spec/worker/transporter/parseSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/checkException.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/determineSentencePartIsPassive.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getSentencePartsSplitOnStopwords.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoice.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoiceResult.js
  packages/yoastseo/src/languageProcessing/values/Sentence.js
  packages/yoastseo/src/languageProcessing/values/index.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/values/Participle.js
  packages/yoastseo/src/values/Sentence.js
  packages/yoastseo/src/values/SentencePart.js
  packages/yoastseo/src/values/index.js
  packages/yoastseo/src/worker/transporter/parse.js
Labels: changelog: non-user-facing

#1168 Move language specific getClauses code
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getClausesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/getClausesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getClauses.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/getClauses.js
Labels: changelog: non-user-facing

#1175 Improve Czech stopwords list
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWordsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/getClausesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getClauses.js
Labels: changelog: enhancement

#1177 Remove whitespace from not-present ShoppingData from Google Preview
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: bugfix

#1179 Use `yarn tsc` instead of `tsc`
  packages/schema-blocks/package.json
Labels: changelog: non-user-facing, tooling

#1174 Placeholder attribute is not output on frontend anymore.
  packages/schema-blocks/src/instructions/blocks/Heading.tsx
  packages/schema-blocks/src/instructions/blocks/RichText.ts
  packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
Labels: changelog: bugfix, innovation

#1180 Update Google preview ShoppingData layout
  packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
  packages/search-metadata-previews/src/snippet-preview/ProductDataMobile.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: bugfix

#1182 Bump @wordpress/data to the latest version
  packages/schema-blocks/package.json
  yarn.lock
Labels: changelog: non-user-facing

#1183 P1 488 shoppingdata availability typography
  packages/search-metadata-previews/src/snippet-preview/ProductDataDesktop.js
  packages/search-metadata-previews/src/snippet-preview/ProductDataMobile.js
Labels: changelog: non-user-facing
