Repository Yoast/javascript, pull requests merged in 2021-02, with the labels that each got.

#1030 Added readme and changelog for the @yoast/schema-blocks package
  README.md
  packages/schema-blocks/CHANGELOG.md
  packages/schema-blocks/README.md
Labels: changelog: non-user-facing

#1036 Set width and max-width for image-select-preview
  packages/components/src/image-select/image-select.css
Labels: UI change, changelog: bugfix

#1035 Adapt Norwegian and Turkish to new structure
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/tr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/nb/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/nb/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/tr/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/internal/nonPassiveExceptions.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/internal/passiveEndings.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/tr/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/tr/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/tr/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoice.js
  packages/yoastseo/vendor/turkishStemmer.js
Labels: changelog: non-user-facing

#1014 P2-252 - Date instruction for Schema blocks package
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/package.json
  packages/schema-blocks/src/instructions/blocks/Date.tsx
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/type-adapters/wordpress__date-adapter.d.ts
  packages/schema-blocks/tests/instructions/blocks/Date.test.ts
  packages/schema-blocks/tests/instructions/blocks/Select.test.ts
  packages/schema-blocks/tests/instructions/blocks/__snapshots__/Date.test.ts.snap
  yarn.lock
Labels: changelog: enhancement, innovation

#1038 Added default option to VariableRichText and made sure required- and recommmendedBlocks in the InnerBlocks block instruction are always an array.
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
Labels: changelog: non-user-facing, innovation

#1039 Add missing specs for Hebrew, Hungarian, and Swedish morphology/readability files
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/he/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/he/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/he/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/values/HungarianParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/values/SentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sv/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceHebrewSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceHungarianSpec.js
  packages/yoastseo/src/languageProcessing/languages/hu/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/hu/values/SentencePart.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/functionWords.js
Labels: changelog: non-user-facing

#1027 Refactor integration
  apps/content-analysis/src/App.js
  apps/content-analysis/src/analysis.worker.js
  apps/content-analysis/src/components/Inputs.js
  apps/content-analysis/src/components/ScoreIcon.js
  apps/content-analysis/src/index.js
  apps/content-analysis/src/redux/utils/StoreSubscriber.js
  apps/content-analysis/src/utils/calculateProminentWords.js
  apps/content-analysis/src/utils/formatAnalyzeResult.js
  packages/yoastseo/index.js
  packages/yoastseo/src/app.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/parsedPaper/build/linguisticParsing/SentenceTokenizer.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/paragraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
  packages/yoastseo/src/scoring/assessor.js
  packages/yoastseo/src/scoring/helpers/assessments/recommendedKeywordCount.js
  packages/yoastseo/src/snippetPreview/snippetPreview.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#1041 Add or modify specs for researches files part 3
  packages/yoastseo/spec/languageProcessing/researches/h1sSpec.js
  packages/yoastseo/spec/languageProcessing/researches/imageCountInTextSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseLengthSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountInUrlSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/languageProcessing/researches/matchKeywordInSubheadingsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
Labels: changelog: non-user-facing

#1042 Add or adjust specs for research files part 4
  packages/yoastseo/spec/assessments/urlLengthSpec.js
  packages/yoastseo/spec/assessments/urlStopWordsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionLengthSpec.js
  packages/yoastseo/spec/languageProcessing/researches/pageTitleWidthSpec.js
  packages/yoastseo/spec/languageProcessing/researches/readingTimeSpec.js
  packages/yoastseo/spec/languageProcessing/researches/stopWordsInKeywordSpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordCountInTextSpec.js
  packages/yoastseo/spec/researches/getWordComplexitySpec.js
  packages/yoastseo/spec/researches/metaDescriptionLengthSpec.js
  packages/yoastseo/spec/researches/readingTimeSpec.js
  packages/yoastseo/spec/researches/stopWordsInUrlSpec.js
  packages/yoastseo/spec/researches/urlIsTooLongSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/he/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/id/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ru/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sv/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/tr/Researcher.js
  packages/yoastseo/src/languageProcessing/researches/stopWordsInUrl.js
  packages/yoastseo/src/languageProcessing/researches/urlLength.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/seo/UrlLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/urlStopWordsAssessment.js
Labels: changelog: non-user-facing

#1043 Refactored Select block instruction and added TextInput block instruction.
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/instructions/blocks/CurrencySelect.tsx
  packages/schema-blocks/src/instructions/blocks/Select.tsx
  packages/schema-blocks/src/instructions/blocks/TextInput.tsx
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/leaves/blocks/BlockElementLeaf.ts
  packages/schema-blocks/tests/instructions/blocks/Select.test.ts
  packages/schema-blocks/tests/instructions/blocks/__snapshots__/Select.test.ts.snap
Labels: changelog: non-user-facing, innovation

#1044 Allow a different default image to be passed to the ImageSelect
  packages/components/src/image-select/ImageSelect.js
Labels: changelog: non-user-facing

#1029 Create job location variations
  packages/schema-blocks/package.json
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/schema/SchemaDefinition.ts
  packages/schema-blocks/src/functions/blocks/recurseOverBlocks.ts
  packages/schema-blocks/src/instructions/blocks/Block.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
  packages/schema-blocks/src/instructions/blocks/Variation.ts
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/instructions/schema/Attribute.ts
  packages/schema-blocks/src/instructions/schema/BlockId.ts
  packages/schema-blocks/src/instructions/schema/HTML.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocks.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksHTML.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksID.ts
  packages/schema-blocks/src/instructions/schema/List.ts
  packages/schema-blocks/src/instructions/schema/Permalink.ts
  packages/schema-blocks/src/instructions/schema/Schema.ts
  packages/schema-blocks/src/type-adapters/ExtendedBlockConfiguration.ts
  packages/schema-blocks/tests/instructions/blocks/Select.test.ts
  yarn.lock
Labels: UI change, changelog: non-user-facing, innovation

#1032 Refactor sentence length and Flesch reading ease assessments to get scores config from the researcher
  packages/yoastseo/spec/assessments/fleschReadingEaseAssessmentSpec.js
  packages/yoastseo/spec/assessments/fleschReadingEaseSpec.js
  packages/yoastseo/spec/assessments/sentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/he/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/ResearcherSpec.js
  packages/yoastseo/spec/specHelpers/factory.js
  packages/yoastseo/src/config/_todo/content/ca.js
  packages/yoastseo/src/config/_todo/content/combinedConfig.js
  packages/yoastseo/src/config/_todo/content/default.js
  packages/yoastseo/src/config/_todo/content/es.js
  packages/yoastseo/src/config/_todo/content/it.js
  packages/yoastseo/src/config/_todo/content/pl.js
  packages/yoastseo/src/config/_todo/content/pt.js
  packages/yoastseo/src/config/_todo/content/ru.js
  packages/yoastseo/src/config/_todo/syllables.js
  packages/yoastseo/src/config/config.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/es/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/es/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/he/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/he/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/hu/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/it/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/it/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/pl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/pt/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/ru/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/fleschReadingEaseScores.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/sv/Researcher.js
  packages/yoastseo/src/scoring/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/helpers/assessments/checkForTooLongSentences.js
Labels: changelog: non-user-facing

#1046 Added SidebarCheckbox instruction, JobEmploymentType instruction.
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/instructions/blocks/SidebarCheckbox.tsx
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/instructions/schema/JobEmploymentType.ts
  packages/schema-blocks/src/instructions/schema/index.ts
Labels: UI change, changelog: non-user-facing, innovation

#1047 QAK-2652 Add missing focus style to checkbox and radio button.
  apps/components/InputsWrapper.js
  packages/components/src/checkbox/checkbox.css
  packages/components/src/radiobutton/radiobutton.css
  packages/components/src/radiobutton/radiobutton.html
Labels: changelog: bugfix

#1052 P2-560 Replace console.logs with logger
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/functions/gutenberg/filter.ts
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/logger.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/index.ts
Labels: changelog: non-user-facing, changelog: other, innovation

#1051 Use proper textdomains
  packages/schema-blocks/src/blocks/warning-block/edit.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
Labels: changelog: non-user-facing

#1040 P2 364 block removal warnings
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/package.json
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/validators/isValidResult.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/InnerBlocksInstructionOptions.ts
  packages/schema-blocks/src/leaves/schema/SchemaInterpolatedLeaf.ts
  packages/schema-blocks/src/type-adapters/yoast__components.d.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/process.test.ts
  packages/schema-blocks/tests/instructions/Innerblocks.test.ts
  yarn.lock
Labels: UI change, changelog: non-user-facing, innovation

#1054 Adjusted the findKeywordInFirstParagraph spec
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
Labels: changelog: non-user-facing, innovation

#1053 added a 250ms debounce to the gutenberg subscriber
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  yarn.lock
Labels: changelog: non-user-facing, innovation

#1055 Add sentence length config for Turkish
  packages/yoastseo/spec/assessments/sentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/languageProcessing/languages/tr/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/tr/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/sentenceLength.js
Labels: changelog: non-user-facing, innovation

#1056 Add specs for catalan and default researcher and helper
  packages/yoastseo/spec/languageProcessing/languages/_default/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/_default/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ca/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ca/helpers/getStemmerSpec.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ca/Researcher.js
Labels: changelog: non-user-facing, innovation

#1050 Added missing React key attributes.
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
Labels: changelog: non-user-facing, innovation

#1057 Added default class name to select instruction in schema blocks.
  packages/schema-blocks/src/instructions/blocks/Select.tsx
Labels: changelog: non-user-facing

#1045 Implement Video in Elementor editor
  packages/components/src/image-select/image-select.css
Labels: changelog: non-user-facing

#1058 Show a placeholder first instead of setting todays date as default
  packages/schema-blocks/src/instructions/blocks/Date.tsx
Labels: changelog: non-user-facing, innovation

#1060 Removes the prepare hook in the package.json.
  packages/schema-blocks/package.json
Labels: changelog: non-user-facing

#1059 Delete language-specific matchParticiplesSpec
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceHebrewSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceHungarianSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesDutchSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesEnglishSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesItalianSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesPolishSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesPortugueseSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesSpanishSpec.js
Labels: changelog: non-user-facing, innovation

#1063 P2 671 analysis for job posting not always shown
  packages/schema-blocks/src/instructions/blocks/Block.ts
  packages/schema-blocks/src/instructions/blocks/Block.tsx
Labels: UI change, changelog: enhancement, innovation

#1061 Adapt full text tests
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
Labels: changelog: non-user-facing, innovation

#1064 Delete sentenceLengthInDescriptionAssessment and its research file
  packages/yoastseo/spec/languageProcessing/researches/countSentencesFromDescriptionSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/sentenceLengthInDescriptionAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/countSentencesFromDescription.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInDescriptionAssessment.js
Labels: changelog: non-user-facing, innovation

#1065 Always add 'yoast-inner-container' classes on the frontend.
  packages/schema-blocks/src/instructions/blocks/ClassName.ts
  packages/schema-blocks/tests/instructions/blocks/ClassName.test.ts
Labels: UI change, changelog: bugfix, innovation

#1067 Generating instruction IDs now skips IDs that also occur in the separator.
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/tests/functions/process.test.ts
Labels: changelog: bugfix

#1048 add isAlertDismissed prop to Alert component
  packages/components/src/Alert.js
Labels: changelog: non-user-facing, innovation

#1068 Refactor sentenceLengthInText assessment so that it can use language-specific cornerstone config
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/languageProcessing/languages/pl/ResearcherSpec.js
  packages/yoastseo/spec/scoring/SEOAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/sentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessorSpec.js
  packages/yoastseo/spec/scoring/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/SEOAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/relatedKeywordTaxonomyAssessorSpec.js
  packages/yoastseo/spec/scoring/taxonomyAssessorSpec.js
  packages/yoastseo/src/languageProcessing/languages/pl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/sentenceLength.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing, innovation

#1070 Add passive voice assessment for Czech
  packages/yoastseo/spec/languageProcessing/languages/cz/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cz/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cz/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cz/values/CzechParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceCzechSpec.js
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/internal/passiveVoiceEndings.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/cz/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/cz/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/cz/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/cz/values/CzechParticiple.js
  packages/yoastseo/src/languageProcessing/languages/cz/values/SentencePart.js
Labels: changelog: enhancement

#1072 Remove language specific researcher from index.js
  apps/content-analysis/src/analysis.worker.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/fleschReadingEaseAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/passiveVoiceAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/sentenceBeginningsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/transitionWordsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/wordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextCompetingLinksAssessmentSpec.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: non-user-facing, innovation

#1077 P1 397 expose checkbox
  packages/components/src/checkbox/index.js
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/field-group/field-group.css
Labels: changelog: enhancement, innovation

#1075 Lingo 667 deprecate unused prominent words functionality
  packages/yoastseo/spec/stringProcessing/determineProminentWordsDutchSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsEnglishSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsFrenchSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsGermanSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsItalianSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsPolishSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsPortugueseSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsSpanishSpec.js
  packages/yoastseo/spec/stringProcessing/determineProminentWordsSwedishSpec.js
  packages/yoastseo/spec/values/WordCombinationSpec.js
  packages/yoastseo/spec/worker/transporter/parseSpec.js
  packages/yoastseo/src/languageProcessing/helpers/prominentWords/determineProminentWords.js
  packages/yoastseo/src/values/ProminentWord.js
  packages/yoastseo/src/values/WordCombination.js
Labels: changelog: non-user-facing, innovation

#1066 P2 681 add inherit sidebar block
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/functions/gutenberg/block.ts
  packages/schema-blocks/src/functions/gutenberg/sidebar.ts
  packages/schema-blocks/src/instructions/blocks/Block.tsx
  packages/schema-blocks/src/instructions/blocks/InheritSidebar.tsx
  packages/schema-blocks/src/instructions/blocks/SidebarCheckbox.tsx
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/src/instructions/blocks/SidebarInput.ts
  packages/schema-blocks/src/instructions/blocks/SidebarSelect.ts
  packages/schema-blocks/src/instructions/blocks/abstract/SidebarBase.ts
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/src/leaves/schema/SchemaInterpolatedLeaf.ts
Labels: UI change, changelog: other, innovation

#1076 Add full text tests for Catalan
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
Labels: changelog: non-user-facing

#1079 Add Czech function words
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/functionWords.js
Labels: changelog: enhancement
