Repository Yoast/javascript, pull requests merged in 2021-05, with the labels that each got.

#1184 P2-918 - Remove unwanted space in select instruction.
  packages/schema-blocks/src/instructions/blocks/Select.tsx
  packages/schema-blocks/tests/instructions/blocks/__snapshots__/Select.test.ts.snap
Labels: changelog: bugfix, innovation

#1186 Update README.md with Norwegian function words
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#1187 Add missing Polish transition word
  packages/yoastseo/src/researches/polish/transitionWords.js
Labels: changelog: enhancement

#1146 P2 786 only render ok when block is valid
  packages/schema-blocks/jest.config.js
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/blocks/BlockInstructionClass.ts
  packages/schema-blocks/src/core/blocks/index.ts
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/core/validation/index.ts
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/src/functions/validators/defaultValidate.ts
  packages/schema-blocks/src/functions/validators/getAllDescendantIssues.ts
  packages/schema-blocks/src/functions/validators/getPresence.ts
  packages/schema-blocks/src/functions/validators/getValidationResult.ts
  packages/schema-blocks/src/functions/validators/index.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/functions/validators/recursivelyFind.ts
  packages/schema-blocks/src/functions/validators/validateResults.ts
  packages/schema-blocks/src/instructions/blocks/Date.tsx
  packages/schema-blocks/src/instructions/blocks/Heading.tsx
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/instructions/blocks/Select.tsx
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/src/instructions/blocks/TextInput.tsx
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
  packages/schema-blocks/src/instructions/blocks/abstract/RichTextBase.ts
  packages/schema-blocks/tests/core/blocks/BlockInstruction.test.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  packages/schema-blocks/tests/functions/presenters/BlockSuggestions.test.ts
  packages/schema-blocks/tests/functions/presenters/BlockSuggestionsPresenter.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestions.test.ts.snap
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestionsPresenter.test.ts.snap
  packages/schema-blocks/tests/functions/validators/defaultValidation.test.ts
  packages/schema-blocks/tests/functions/validators/getValidationResultForClientId.test.ts
  packages/schema-blocks/tests/instructions/blocks/Date.test.ts
  packages/schema-blocks/tests/instructions/blocks/Select.test.ts
Labels: changelog: bugfix, innovation

#1176 Add the title field to the sidebar
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/presenters/HelpLinkPresenter.tsx
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebar.tsx
  packages/schema-blocks/src/functions/presenters/LabelWithHelpLinkPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/instructions/blocks/InheritSidebar.tsx
  packages/schema-blocks/src/instructions/blocks/SidebarInput.ts
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/abstract/SidebarBase.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
Labels: UI change, changelog: enhancement, innovation

#1178 P2 877 fix jobs html
  packages/schema-blocks/src/instructions/blocks/ClassName.ts
  packages/schema-blocks/src/instructions/blocks/Date.tsx
  packages/schema-blocks/src/instructions/blocks/Select.tsx
  packages/schema-blocks/tests/instructions/blocks/ClassName.test.ts
  packages/schema-blocks/tests/instructions/blocks/__snapshots__/Date.test.ts.snap
Labels: changelog: enhancement, innovation

#1196 P2-948 - Make the Schema analysis work with blocks
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/redux/reducer/schemaBlocks.ts
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/src/functions/validators/missingBlocks.ts
  packages/schema-blocks/src/index.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/tests/functions/presenters/BlockSuggestionsPresenter.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/presenters/__snapshots__/BlockSuggestionsPresenter.test.ts.snap
  packages/schema-blocks/tests/functions/validators/defaultValidation.test.ts
  packages/schema-blocks/tests/functions/validators/getValidationResultForClientId.test.ts
  packages/schema-blocks/tests/instructions/blocks/Date.test.ts
Labels: changelog: other, innovation
