Repository Yoast/javascript, pull requests merged in 2021-01, with the labels that each got.

#989 Add function words for Turkish
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/researches/turkish/functionWords.js
Labels: changelog: enhancement

#974 Add passive voice assessment for Turkish
  packages/yoastseo/spec/researches/getPassiveVoiceTurkishSpec.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
  packages/yoastseo/src/researches/turkish/passiveVoice/nonPassivesTurkish.js
  packages/yoastseo/src/researches/turkish/passiveVoice/passiveEndings.js
Labels: changelog: enhancement

#973 Add unit tests for sanitize helpers part 2
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeStringSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripHTMLTagsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripNonTextTagsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripNumbersSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripSpacesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripWordBoundariesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/unifyWhitespaceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripHTMLTags.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripNumbers.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripSpaces.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/unifyWhitespace.js
Labels: changelog: non-user-facing

#980 Add unit tests for sentence helpers
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/countSentencesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js
  packages/yoastseo/spec/stringProcessing/sentencesLengthSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/countSentences.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/sentencesLength.js
Labels: changelog: non-user-facing

#991 P2-215 Create Select instruction.
  packages/schema-blocks/.eslintrc
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/jest.config.js
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/functions/validators/index.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/Select.tsx
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/tests/blocks/warning-block/edit.test.ts
  packages/schema-blocks/tests/instructions/blocks/Select.test.ts
  packages/schema-blocks/tests/instructions/blocks/__snapshots__/Select.test.ts.snap
Labels: changelog: non-user-facing, innovation

#994 Update README.md for Turkish readability
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#983 Add unit tests for transliterate helpers
  packages/yoastseo/spec/languageProcessing/helpers/transliterate/replaceDiacriticsSpecs.js
  packages/yoastseo/spec/languageProcessing/helpers/transliterate/specialCharacterMappingsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/transliterate/transliterateSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/transliterate/transliterateWPstyleSpec.js
  packages/yoastseo/src/config/diacritics.js
  packages/yoastseo/src/config/transliterations.js
  packages/yoastseo/src/config/transliterationsWPstyle.js
  packages/yoastseo/src/languageProcessing/helpers/transliterate/replaceDiacritics.js
  packages/yoastseo/src/languageProcessing/helpers/transliterate/specialCharacterMappings.js
  packages/yoastseo/src/languageProcessing/helpers/transliterate/transliterate.js
  packages/yoastseo/src/languageProcessing/helpers/transliterate/transliterateWPstyle.js
Labels: changelog: non-user-facing

#986 Add sentence beginnings assessment for Turkish
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/researches/turkish/firstWordExceptions.js
Labels: changelog: enhancement

#979 P2-505 Adds required blocks to sidebar
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/jest.config.js
  packages/schema-blocks/src/blocks/RequiredBlocks.tsx
  packages/schema-blocks/src/functions/BlockHelper.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/enums/RequiredBlockOption.ts
  packages/schema-blocks/tests/blocks/RequiredBlocks.test.ts
  packages/schema-blocks/tests/blocks/__snapshots__/RequiredBlocks.test.ts.snap
  packages/schema-blocks/tests/functions/BlocksHelper.test.ts
  packages/schema-blocks/tests/functions/process.test.ts
Labels: UI change, innovation

#985 Add specs for url helpers
  packages/yoastseo/spec/languageProcessing/helpers/url/parseSlugSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/url/urlSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/url/urlStructureSpec.js
  packages/yoastseo/src/languageProcessing/helpers/url/urlStructure.js
Labels: changelog: non-user-facing

#981 Add Turkish Stemmer
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/Gruntfile.js
  packages/yoastseo/grunt/config/babel.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/turkish/stemSpec.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/turkish/stem.js
  packages/yoastseo/vendor/turkishStemmer.js
Labels: changelog: enhancement

#998 Add missing closing bracket in CSS file.
  packages/schema-blocks/css/schema-blocks.css
Labels: changelog: non-user-facing, innovation

#1002 Add full text specs for Turkish
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
Labels: changelog: non-user-facing

#1005 No longer make Lerna ignore changes made to the schema-blocks package
  lerna.json
Labels: changelog: non-user-facing

#1004 Add missing specs for Turkish stemmer
  packages/yoastseo/spec/morphology/turkish/stemSpec.js
Labels: changelog: non-user-facing

#1003 LINGO-611 Merge Turkish feature branch
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/Gruntfile.js
  packages/yoastseo/README.md
  packages/yoastseo/grunt/config/babel.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/assessments/sentenceBeginningsSpec.js
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/helpers/getFirstWordExceptionsSpec.js
  packages/yoastseo/spec/helpers/getFunctionWordsLanguagesSpec.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/spec/morphology/turkish/stemSpec.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/morphology/turkish/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/researches/buildTopicStemsSpec.js
  packages/yoastseo/spec/researches/getPassiveVoiceTurkishSpec.js
  packages/yoastseo/spec/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/config/content/combinedConfig.js
  packages/yoastseo/src/config/content/tr.js
  packages/yoastseo/src/helpers/getFirstWordExceptions.js
  packages/yoastseo/src/helpers/getFunctionWords.js
  packages/yoastseo/src/helpers/getStemForLanguage.js
  packages/yoastseo/src/morphology/turkish/stem.js
  packages/yoastseo/src/researches/getPassiveVoice.js
  packages/yoastseo/src/researches/passiveVoice/morphological/determinePassiveSentence.js
  packages/yoastseo/src/researches/turkish/firstWordExceptions.js
  packages/yoastseo/src/researches/turkish/functionWords.js
  packages/yoastseo/src/researches/turkish/passiveVoice/nonPassivesTurkish.js
  packages/yoastseo/src/researches/turkish/passiveVoice/passiveEndings.js
  packages/yoastseo/vendor/turkishStemmer.js
Labels: changelog: enhancement

#1007 Add Turkish transition words assessment
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/helpers/getTransitionWordsSpec.js
  packages/yoastseo/spec/researches/findTransitionWordsSpec.js
  packages/yoastseo/src/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/helpers/getTransitionWords.js
  packages/yoastseo/src/researches/turkish/transitionWords.js
  packages/yoastseo/src/researches/turkish/twoPartTransitionWords.js
Labels: changelog: enhancement

#1000 Fix app/components
  apps/components/AppWrapper.js
  apps/components/ReactifiedComponentsWrapper.js
  apps/components/package.json
  apps/components/webpack.config.js
  packages/analysis-report/package.json
  packages/components/package.json
  packages/configuration-wizard/package.json
  packages/helpers/package.json
  packages/schema-blocks/package.json
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/package.json
  packages/yoast-components/package.json
  yarn.lock
Labels: changelog: non-user-facing

#996 Add unit tests for Arabic helpers
  packages/yoastseo/spec/languageProcessing/languages/ar/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/createBasicWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/ar/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/morphology/arabic/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/languages/ar/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ar/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/internal/stem.js
  packages/yoastseo/src/markers/addMarkSingleWord.js
Labels: changelog: non-user-facing

#1006 Create DurationInput component
  apps/components/ReactifiedComponentsWrapper.js
  packages/components/src/inputs/DurationInput.js
  packages/components/src/inputs/input.css
  packages/components/tests/inputs/DurationInputTest.js
Labels: changelog: enhancement

#997 Create ImageSelect component
  apps/components/App.js
  apps/components/ButtonsOldWrapper.js
  apps/components/ButtonsWrapper.js
  apps/components/ImageSelectWrapper.js
  apps/components/InputsWrapper.js
  apps/components/tests/__snapshots__/appTest.js.snap
  packages/components/src/base/icons.css
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/image-select/ImageSelectButtons.js
  packages/components/src/image-select/image-select.css
  packages/components/src/image-select/index.js
  packages/components/src/index.js
  packages/components/src/inputs/TextArea.js
  packages/components/src/inputs/TextInput.js
  packages/components/tests/ImageSelectButtonsTest.js
  packages/components/tests/ImageSelectTest.js
  packages/components/tests/__snapshots__/ImageSelectButtonsTest.js.snap
  packages/components/tests/__snapshots__/ImageSelectTest.js.snap
Labels: changelog: enhancement

#987 Add unit tests for word helpers
  packages/yoastseo/spec/helpers/filterFunctionWordsFromArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/addWordBoundarySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/areWordsInSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/countWordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/filterWordsFromArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/followsIndexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getVariationsApostropheSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/includesIndexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/indicesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/matchWordInSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/wordsIntextSpec.js
  packages/yoastseo/spec/stringProcessing/addWordBoundarySpec.js
  packages/yoastseo/spec/stringProcessing/countWordsSpec.js
  packages/yoastseo/spec/stringProcessing/markWordsInSentenceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/countWords.js
  packages/yoastseo/src/languageProcessing/helpers/word/filterWordsFromArray.js
  packages/yoastseo/src/languageProcessing/helpers/word/followsIndex.js
  packages/yoastseo/src/languageProcessing/helpers/word/getVariationsApostrophe.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWords.js
  packages/yoastseo/src/languageProcessing/helpers/word/includesIndex.js
  packages/yoastseo/src/languageProcessing/helpers/word/indices.js
  packages/yoastseo/src/languageProcessing/helpers/word/wordsInText.js
Labels: changelog: non-user-facing

#999 Add specs for the German helpers and Researcher
  packages/yoastseo/spec/languageProcessing/languages/de/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/determineStemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/values/GermanParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/values/SentencePartSpec.js
  packages/yoastseo/spec/researches/german/functionWordsSpec.js
  packages/yoastseo/spec/researches/german/passiveVoice/SentencePartSpec.js
  packages/yoastseo/spec/researches/german/passiveVoice/getSentencePartsSpec.js
  packages/yoastseo/spec/researches/german/passiveVoice/regexSpec.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/passiveVoiceRegex.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/isPassiveSentencePart.js
Labels: changelog: non-user-facing

#1009 Add Farsi Researcher and helper specs
  packages/yoastseo/spec/languageProcessing/languages/fa/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fa/helpers/createBasicWordFormsSpec.js
  packages/yoastseo/src/languageProcessing/languages/fa/helpers/createBasicWordForms.js
Labels: changelog: non-user-facing

#1011 Add full text specs for Hungarian
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
Labels: changelog: non-user-facing

#1010 Add specs for Spanish helpers values and researcher
  packages/yoastseo/spec/languageProcessing/languages/es/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/isPassiveSentecePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/values/SentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/values/SpanishParticipleSpec.js
  packages/yoastseo/spec/morphology/spanish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/researches/passiveVoice/getParticiplesSpanishSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsSpanishSpec.js
  packages/yoastseo/spec/researches/spanish/functionWordsSpec.js
  packages/yoastseo/src/languageProcessing/languages/es/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/es/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/stem.js
Labels: changelog: non-user-facing

#1016 Add French helper, value and Researcher specs
  packages/yoastseo/spec/languageProcessing/languages/fr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/values/FrenchParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/values/SentencePartSpec.js
  packages/yoastseo/spec/morphology/french/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/researches/french/functionWordsSpec.js
  packages/yoastseo/spec/researches/french/passiveVoice/FrenchSentencePartSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsFrenchSpec.js
  packages/yoastseo/spec/researches/passiveVoice/matchParticiplesFrenchSpec.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/internal/stem.js
Labels: changelog: non-user-facing

#1013 Add specs for Hebrew helper and researcher
  packages/yoastseo/spec/languageProcessing/languages/he/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/he/helpers/createBasicWordFormsSpec.js
  packages/yoastseo/src/languageProcessing/languages/he/helpers/createBasicWordForms.js
Labels: changelog: non-user-facing

#995 P2-217 Create warning subscriber
  packages/schema-blocks/src/blocks/warning-block/configuration.ts
  packages/schema-blocks/src/blocks/warning-block/edit.ts
  packages/schema-blocks/src/functions/BlockHelper.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/src/functions/innerBlocksHelper.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/dto/RecommendedBlock.ts
  packages/schema-blocks/src/instructions/blocks/dto/RequiredBlock.ts
  packages/schema-blocks/src/instructions/blocks/dto/index.ts
  packages/schema-blocks/tests/blocks/warning-block/configuration.test.ts
  packages/schema-blocks/tests/functions/BlocksHelper.test.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  packages/schema-blocks/tests/functions/innerBlocksHelper.test.ts
Labels: changelog: non-user-facing

#965 Add unit tests for periphrastic passive voice helper files
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/determineSentencePartIsPassiveSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/nonDirectParticiplePrecedenceExceptionSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getIndicesWithRegexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/getSentencePartsSplitOnStopwordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/passiveVoice/periphrastic/matchRegularParticiplesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/nonDirectParticiplePrecedenceException.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/matchRegularParticiples.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/getParticiples.js
Labels: changelog: non-user-facing

#1012 Added keys to elements returned by BlockDefinitions
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
Labels: changelog: bugfix

#1022 Add unit tests for Dutch researcher, value and helper files
  packages/yoastseo/spec/languageProcessing/languages/nl/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/checkExceptionsWithFullFormsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/detectAndStemSuffixesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/determineStemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/getStemWordsWithTAndDEndingSpecs.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/stemModificationHelpersSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/internal/stemTOrDFromEndOfWordSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/values/DutchParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nl/values/SentencePartSpec.js
  packages/yoastseo/spec/researches/dutch/functionWordsSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getParticiplesDutchSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsDutchSpec.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/detectAndStemRegularParticiple.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/detectAndStemSuffixes.js
  packages/yoastseo/src/languageProcessing/languages/nl/helpers/internal/stemModificationHelpers.js
  packages/yoastseo/src/languageProcessing/languages/nl/values/DutchParticiple.js
Labels: changelog: non-user-facing

#1018 Add specs for Polish helpers, values and Researcher
  packages/yoastseo/spec/languageProcessing/languages/pl/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/pl/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/values/PolishParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pl/values/SentencePartSpec.js
  packages/yoastseo/spec/morphology/polish/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsPolishSpec.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/internal/auxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/stopwords.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/pl/helpers/isPassiveSentencePart.js
Labels: changelog: non-user-facing

#1024 Change boundaries for Turkish sentence length assessment
  packages/yoastseo/spec/assessments/sentenceLengthInTextSpec.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/src/config/content/tr.js
Labels: changelog: non-user-facing

#1017 Add specs for Italian files
  packages/yoastseo/spec/languageProcessing/languages/it/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/values/ItalianParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/values/SentencePartSpec.js
  packages/yoastseo/spec/researches/italian/functionWordsSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getParticiplesItalianSpec.js
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsItalianSpec.js
  packages/yoastseo/src/languageProcessing/languages/it/config/functionWords.js
Labels: changelog: non-user-facing

#1015 Add specs for Indonesian helpers and researcher
  packages/yoastseo/spec/languageProcessing/languages/id/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemHelpersSpec.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/id/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/morphology/indonesian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/languages/id/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/id/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/id/config/internal/nonPassiveVerbsStartingDi.js
  packages/yoastseo/src/languageProcessing/languages/id/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/id/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stemHelpers.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/isPassiveSentence.js
Labels: changelog: non-user-facing

#1020 Fixed multiple unique key warnings.
  packages/schema-blocks/src/blocks/RequiredBlocks.tsx
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/SidebarDuration.ts
  packages/schema-blocks/src/leaves/blocks/BlockElementLeaf.ts
Labels: changelog: bugfix

#1021 Add specs for Portuguese helpers, values and Researcher
  packages/yoastseo/spec/languageProcessing/languages/pt/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/values/PortugueseParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/pt/values/SentencePartSpec.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/portuguese/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/researches/passiveVoice/getSentencePartsPortugueseSpec.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/pt/values/PortugueseParticiple.js
Labels: changelog: non-user-facing

#992 P2 281 add schema validation to the store
  packages/schema-blocks/src/blocks/RequiredBlocks.tsx
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinition.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/schema/SchemaInstruction.ts
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/core/validation/RecommendedBlock.ts
  packages/schema-blocks/src/core/validation/RequiredBlock.ts
  packages/schema-blocks/src/core/validation/RequiredBlockOption.ts
  packages/schema-blocks/src/core/validation/index.ts
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/src/functions/process.ts
  packages/schema-blocks/src/functions/validators/index.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/functions/validators/isValidResult.ts
  packages/schema-blocks/src/functions/validators/validateMany.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.ts
  packages/schema-blocks/src/instructions/blocks/RichText.ts
  packages/schema-blocks/src/instructions/blocks/abstract/SidebarBase.ts
  packages/schema-blocks/src/instructions/blocks/dto/InvalidBlock.ts
  packages/schema-blocks/src/instructions/blocks/dto/index.ts
  packages/schema-blocks/src/instructions/blocks/enums/InvalidBlockReason.ts
  packages/schema-blocks/src/instructions/blocks/enums/index.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocks.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksHTML.ts
  packages/schema-blocks/src/instructions/schema/InnerBlocksID.ts
  packages/schema-blocks/tests/blocks/RequiredBlocks.test.ts
  packages/schema-blocks/tests/core/Definition.test.ts
  packages/schema-blocks/tests/core/blocks/BlockInstruction.test.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  packages/schema-blocks/tests/functions/process.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
  packages/schema-blocks/tests/functions/validators/validateMany.test.ts
  packages/schema-blocks/tests/instructions/Innerblocks.test.ts
  packages/schema-blocks/yarn.lock
Labels: changelog: non-user-facing, innovation

#1026 Update DurationInput component to just handle a duration in seconds
  apps/components/InputsWrapper.js
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/field-group/field-group.css
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/image-select/ImageSelectButtons.js
  packages/components/src/image-select/image-select.css
  packages/components/src/inputs/DurationInput.js
  packages/components/tests/ImageSelectButtonsTest.js
  packages/components/tests/__snapshots__/ImageSelectButtonsTest.js.snap
  packages/components/tests/__snapshots__/ImageSelectTest.js.snap
  packages/components/tests/inputs/DurationInputTest.js
Labels: Package: components, changelog: other, innovation

#1023 Improve ImageSelect component
  apps/components/SocialPreviewEditorWrapper.js
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/image-select/image-select.css
  packages/components/tests/__snapshots__/ImageSelectTest.js.snap
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
Labels: UI change, changelog: enhancement, changelog: non-user-facing, innovation

#1028 Add specs for Russian helpers and Researcher
  packages/yoastseo/spec/languageProcessing/languages/ru/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/calculateFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/ru/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/morphology/russian/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/languages/ru/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/internal/stem.js
Labels: changelog: non-user-facing

#1025 Add specs for Swedish helper and Researcher file
  packages/yoastseo/spec/languageProcessing/languages/sv/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sv/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/internal/passiveVerbs.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/helpers/isPassiveSentence.js
Labels: changelog: non-user-facing

#1001 P2 506 add recommended blocks to sidebar
  packages/schema-blocks/src/blocks/BlockSuggestions.tsx
  packages/schema-blocks/src/core/validation/RecommendedBlock.ts
  packages/schema-blocks/src/core/validation/RequiredBlock.ts
  packages/schema-blocks/src/core/validation/SuggestedBlockProperties.ts
  packages/schema-blocks/src/core/validation/index.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/src/leaves/blocks/BlockInstructionLeaf.ts
  packages/schema-blocks/tests/blocks/BlockSuggestions.test.ts
  packages/schema-blocks/tests/blocks/__snapshots__/BlockSuggestions.test.ts.snap
  packages/schema-blocks/tests/functions/process.test.ts
Labels: UI change, changelog: non-user-facing, innovation

#1033 Add specs for researches part 1
  packages/yoastseo/spec/languageProcessing/researches/altTagCountSpec.js
  packages/yoastseo/spec/languageProcessing/researches/countSentencesFromDescriptionSpec.js
  packages/yoastseo/spec/languageProcessing/researches/countSentencesFromTextSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/functionWordsInKeyphraseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getFleschReadingScoreSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getKeywordDensitySpec.js
  packages/yoastseo/spec/researches/calculateFleschReadingSpec.js
  packages/yoastseo/spec/researches/getKeywordDensitySpec.js
  packages/yoastseo/src/languageProcessing/languages/_default/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/_default/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/ca/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ca/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/hu/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/hu/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/researches/altTagCount.js
  packages/yoastseo/src/languageProcessing/researches/findTransitionWords.js
Labels: changelog: non-user-facing
