Repository Yoast/javascript, pull requests merged in 2021-03, with the labels that each got.

#1080 Add full text tests for Dutch
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper3.js
Labels: changelog: non-user-facing

#1082 Add full text tests for Indonesian
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
Labels: changelog: non-user-facing

#1083 Add Farsi full text tests
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
Labels: changelog: non-user-facing

#1084 Fix code style errors
  packages/yoastseo/spec/languageProcessing/helpers/regex/matchStringWithRegexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/hu/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountInUrlSpec.js
  packages/yoastseo/spec/worker/transporter/parseSpec.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/getVerbStem.js
  packages/yoastseo/src/languageProcessing/languages/es/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/hu/helpers/isPassiveSentence.js
  packages/yoastseo/src/languageProcessing/languages/index.js
Labels: changelog: non-user-facing

#1087 Remove accidentally added package-lock.json files
  apps/content-analysis/package-lock.json
  packages/yoastseo/package-lock.json
Labels: changelog: non-user-facing

#1085 SnippetPreview: Change the desktop mode URL
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/SnippetEditorTest.js
  packages/search-metadata-previews/tests/SnippetPreviewTest.js
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: changelog: enhancement

#1090 Add Portuguese full text tests
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper3.js
Labels: changelog: non-user-facing

#1086 Add Czech transition words
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/twoPartTransitionWords.js
Labels: changelog: enhancement

#1078 Add checkbox component
  packages/components/src/Checkbox.js
  packages/components/src/checkbox/Checkbox.js
  packages/components/src/checkbox/checkbox.html
  packages/components/src/checkbox/index.js
  packages/components/src/index.js
  packages/components/tests/CheckboxTest.js
  packages/components/tests/__snapshots__/CheckboxTest.js.snap
Labels: changelog: enhancement, innovation

#1081 Add irregular Czech nouns
  packages/yoastseo/spec/languageProcessing/languages/cz/helpers/internal/stemSpec.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/cz/helpers/internal/stem.js
Labels: changelog: non-user-facing

#1074 Refactor integration
  apps/content-analysis/src/utils/runKeyphraseAnalysis.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/yoastseo/index.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getKeywordDensitySpec.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInsightsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getWordFormsSpec.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/helpers/index.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/scoring/assessments/readability/paragraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/textPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing, innovation

#1091 Change the keyphrase density recommended maximum score of dutchPaper1
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper1.js
Labels: changelog: non-user-facing

#1092 Delete link count research file
  packages/yoastseo/examples/PerformanceAnalyses/analysis.js
  packages/yoastseo/spec/languageProcessing/researches/linkCountSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/linkCount.js
Labels: changelog: non-user-facing

#1088 Add Czech sentence beginning assessment
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/firstWordExceptions.js
Labels: changelog: enhancement

#1096 Add get stemmer to Czech researcher
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
Labels: changelog: non-user-facing

#1095 LINGO-685 Make researcher argument of assessor
  packages/yoastseo/spec/pluggableSpec.js
  packages/yoastseo/spec/scoring/assessorSpec.js
  packages/yoastseo/spec/scoring/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/relatedKeywordTaxonomyAssessorSpec.js
  packages/yoastseo/spec/scoring/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/taxonomyAssessorSpec.js
  packages/yoastseo/src/scoring/assessor.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/relatedKeywordTaxonomyAssessor.js
  packages/yoastseo/src/scoring/seoAssessor.js
  packages/yoastseo/src/scoring/taxonomyAssessor.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing, innovation

#1099 Update README.md for Czech readability
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#1098 Fix JS console warnings
  apps/content-analysis/package.json
  packages/components/package.json
  packages/components/src/Collapsible.js
  packages/components/src/select/Select.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
  yarn.lock
Labels: changelog: non-user-facing, technical debt

#1094 Change text results of Portuguese paper
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper2.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
Labels: changelog: non-user-facing

#1101 Add Czech researcher to getResearcher helper
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/languageProcessing/languages/cz/Researcher.js
Labels: changelog: non-user-facing

#1106 Add specs for Researcher and getStemmer
  packages/yoastseo/spec/languageProcessing/languages/cz/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cz/helpers/getStemmerSpec.js
  packages/yoastseo/src/languageProcessing/languages/cz/config/stopWords.js
Labels: changelog: non-user-facing

#1105 Delete helper files that are not used
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removeNonWordCharacterSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/url/urlStructureSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getVariationsApostropheSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/wordsIntextSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removeNonWordCharacters.js
  packages/yoastseo/src/languageProcessing/helpers/url/urlStructure.js
  packages/yoastseo/src/languageProcessing/helpers/word/getVariationsApostrophe.js
  packages/yoastseo/src/languageProcessing/helpers/word/wordsInText.js
Labels: changelog: non-user-facing, innovation

#1107 Add czech full text tests papers
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
Labels: changelog: non-user-facing

#1109 Change locale from cz to cs
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/cs/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/getSentencePartsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/isPassiveSentencePartSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/values/CzechParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoice/getPassiveVoiceCzechSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/languageProcessing/languages/cs/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/internal/passiveVoiceEndings.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getSentenceParts.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/cs/helpers/isPassiveSentencePart.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/CzechParticiple.js
  packages/yoastseo/src/languageProcessing/languages/cs/values/SentencePart.js
Labels: changelog: non-user-facing

#1110 add multiple boolean? to sidebarSelect attributes
  packages/schema-blocks/src/instructions/blocks/SidebarSelect.ts
Labels: changelog: non-user-facing, innovation

#1112 Create a helper for languages with word form support
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  packages/yoastseo/src/helpers/index.js
Labels: changelog: non-user-facing, innovation

#1115 Add Czech to supported languages list
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
Labels: changelog: non-user-facing

#1114 Allow custom labels to be used in the replacement variable editor
  packages/replacement-variable-editor/src/SettingsSnippetEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
Labels: changelog: enhancement

#1117 Shows a link in the warning
  packages/schema-blocks/css/schema-blocks.css
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
Labels: UI change, changelog: bugfix, innovation

#1116 Show an orange bullet in the sidebar analysis when a recommended block is removed
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockInstruction.ts
  packages/schema-blocks/src/core/schema/SchemaInstruction.ts
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/core/validation/RequiredBlock.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/instructions/blocks/InnerBlocks.tsx
  packages/schema-blocks/tests/core/Definition.test.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
  packages/schema-blocks/tests/functions/validators/validateMany.test.ts
Labels: UI change, changelog: enhancement, innovation

#1125 Declare the window object as a type with the specific links
  packages/schema-blocks/src/functions/gutenberg/watchers/warningWatcher.ts
Labels: changelog: non-user-facing

#1131 Use the set date instead of getDate()
  packages/schema-blocks/src/instructions/blocks/Date.tsx
Labels: changelog: non-user-facing, innovation

#1132 Added and refactored exports of the schema-blocks package
  packages/schema-blocks/src/functions/initialize.ts
  packages/schema-blocks/src/index.ts
Labels: changelog: other, innovation

#1129 Added title block instruction.
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/functions/BlockHelper.ts
  packages/schema-blocks/src/functions/presenters/InnerBlocksSidebarPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/src/instructions/blocks/VariableTagRichText.ts
  packages/schema-blocks/src/instructions/blocks/index.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
Labels: changelog: non-user-facing

#1119 P2 694 create schema blocks redux store
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/initialize.ts
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/redux/SchemaBlocksState.ts
  packages/schema-blocks/src/functions/redux/actions/index.ts
  packages/schema-blocks/src/functions/redux/actions/schemaBlocks.ts
  packages/schema-blocks/src/functions/redux/index.ts
  packages/schema-blocks/src/functions/redux/initializeSchemaStore.ts
  packages/schema-blocks/src/functions/redux/reducer/index.ts
  packages/schema-blocks/src/functions/redux/reducer/schemaBlocks.ts
  packages/schema-blocks/src/functions/redux/selectors/index.ts
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/src/index.ts
Labels: changelog: non-user-facing, innovation

#1134 Re-introduces error message when not all required blocks have been filled in.
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/instructions/blocks/Title.tsx
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
Labels: changelog: non-user-facing

#1137 Adapt specs after adding exception stem
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/cs/helpers/internal/stemmerCoverage/goldStandardStems.json
Labels: changelog: non-user-facing
